### ISSUE TITLE
Why is BondImportDirectory hidden from VS project view?

### ISSUE THREAD

**Issue by yilangmok** [microsoft/bond#1003]
Hi!

Why does specifying `BondImportDirectory` hide the directory from the VS project view? It makes it hard to manage my schemas in VS. I'm forced to use the "Show All Files" button, which cause other undesired files to show up. Thanks!

https://github.com/microsoft/bond/blob/8d0842280856f357664d6ea9d3d010497444e8ab/cs/build/nuget/Common.targets#L30-L35

-Yi Lang

**Comment by chwarr** [comment]
I don't remember why it's marked as `<Visible>false</Visible>`. This file came from an older internal version that has had `<Visible>false</Visible>` since 2013. It was introduced as part of a larger refactoring, and the commit history doesn't directly address this. My guess is that it was added to hide deep import chains when usings lots of schemas that depend on each other.

If you want to change this, please submit a PR. Also include a screenshot of VS's Solution Explorer with some example projects that import each other before and after the change to help with the review. Four levels of importing should be sufficient to see if this makes sense to make visible.

**Comment by chwarr** [comment]
I'm going to close this issue for now since I haven't seen any activity in a couple of weeks. If there's something more here, please post another comment. Thanks.
