### ISSUE TITLE
Documents contain incorrect links to .html instead of .md

### ISSUE THREAD

**Issue by chpong** [microsoft/bond#1044]
For example, doc/src/bond_cpp.md has `[syntax]` links to `compiler.html#idl-syntax` instead of `compiler.md#idl-syntax`.

**Comment by chwarr** [comment]
This links to .html files is expected. Otherwise, the [compiled/published documentation](https://microsoft.github.io/bond/) wouldn't work correctly, as Pandoc doesn't know to convert, say, a link to compiler.md to compiler.html during the [documentation build](https://github.com/microsoft/bond/blob/2e7aa1ef70121bc5ec221286d9f0ee3295e1d3b2/doc/CMakeLists.txt).

If you know a way to have Pandoc do this conversion, we'd be happy to integrate that so that the links work both from the documentation source code (the .md files) and the published output (the .html files).
