### ISSUE TITLE
protocol.h(200): error C4296: '<': expression is always false

### ISSUE THREAD

**Issue by abwah** [microsoft/bond#1049]
I am running into this error when compiling a project with a .bond file. Looks like this was reported before as well. what is the solution/workaround for this?

(ClCompile target) ->
         c:\cxcache\bond.cpp.oncorext.8.0.1\lib\native\inc\bond\core\protocol.h(200): error C4296: '<': expression is always false

**Comment by chwarr** [comment]
This was fixed in [Bond 8.2.0](https://github.com/microsoft/bond/blob/master/CHANGELOG.md#820-2019-11-18). If you upgrade to the current version, 9.0, it should go away.

The package of Bond that you're using, Bond.Cpp.OnCoreXT, is one that's only available inside of Microsoft. Follow up questions about it should be directed to the relevant places internally. If you don't know what those are, email my @microsoft.com address from your @microsoft.com address and I'll be happy to point you in the right direction.

**Comment by chwarr** [comment]
I believe this question has been answered, so I'm going to close it. Feel free to reopen with follow ups/more details if not.
