### ISSUE TITLE
Cross-compiling bond

### ISSUE THREAD

**Issue by ardanew** [Microsoft/bond#106]
Want to crosscompile Bond from one linux type to another. What is the requirements for this? Do I required to build an Haskell cross-compliler, a cross-compiled Boost libraries, or some other dependencies?

**Comment by sapek** [comment]
I have never done it but here are some pointers. It will depend if you want to cross-compile Bond and then use it in your build on the target Linux or only cross-compile a program using Bond so that you can run that program on the target Linux.
- Haskell is only needed to build the Bond codegen compiler `gbc`. If you don't need to run codegen on the target Linux than you don't need to cross-compile `gbc`.
- Bond C++ static libraries are only needed if your program needs to de/serialize Bond defined schemas ([`SchemaDef`](https://github.com/Microsoft/bond/blob/57662ca5f4c035295b5a0d11977aae5bfcfc7093/cpp/inc/bond/core/bond.bond#L113-L120) is a common example). Otherwise you can use Bond as a header-only library.
- Bond depends on Boost so you will need to link your program to Boost libraries for the target Linux. You will need `libboost_system` and `libboost_thread` libraries. For Python support you will additionally need to link against `libboost_python`.
