### ISSUE TITLE
Ways to improve performance serializer and deserializer instantiation in C#

### ISSUE THREAD

**Issue by cesarzc** [microsoft/bond#1083]
In a project that I am working on, we are using Bond to do serialization and deserialization using the Simple Binary protocol.

Since we perform multiple deserializations using the same schema, so as advised in the Performance section of the [Bond guide for C#](https://microsoft.github.io/bond/manual/bond_cs.html#performance), we create a Deserializer instance like this:
`var deserializer = new SimpleBinaryDeserializer(typeof(QsCompilation);`

Once the deserializer is instantiated, it has great performance, but it takes a long time to instantiate.

Is there a way to improve Deserializer instantiation performance? Is there a way to make it faster by doing something at compile time?

Thank you for your help!

**Comment by chwarr** [comment]
> Is there a way to improve Deserializer instantiation performance?

See what happens if you [construct the deserializer with `inlineNested: false`](https://github.com/microsoft/bond/blob/a8a56e9f50c9aedfe1234d25be0a47c98e8fbffb/cs/src/core/Deserializer.cs#L131-L140). (You can pass `null` for `factory`.) This may have an impact on your deserialization times, so you'll need to weigh that.

Very little work has been done to optimize the creation of serializers or deserializers. If you profile creation, I'm sure you can find a code change that can speed this up. Such [contributions](https://github.com/microsoft/bond/blob/master/CONTRIBUTING.md) are gladly welcome!

> Is there a way to make it faster by doing something at compile time?

Not really. In C#, today, all the "heavy lifting" happens are runtime. There's an open feature request, [issue #56 "Support a mode without runtime IL generation"](https://github.com/microsoft/bond/issues/56), to shift more to compilation time. There hasn't been much progress on it, and I'm not aware of anyone working on it in the foreseeable future.

-----

If you were using a tagged protocol, a [view](https://microsoft.github.io/bond/manual/compiler.html#struct-views) _might_ speed things up, but that won't work for an untagged protocol like Simple Binary. In a tagged protocol, the deserializer for a view would only have code for the fields in the view. For an untagged protocol, the deserializer needs to know about all the fields in the payload, regardless of the ones mentioned in the view. Which leads me to...

> `var deserializer = new SimpleBinaryDeserializer(typeof(QsCompilation);`

...a general note about using Simple Binary: you typically want to deserialize Simple Binary data using a [`RuntimeSchema`](https://microsoft.github.io/bond/manual/bond_cs.html#runtime-schema) from the writer. That way, you can handle [schema evolution](https://microsoft.github.io/bond/manual/bond_cs.html#schema-evolution) between readers and writers. Without a runtime schema, the reader and the writer must exactly agree on the schema forever.

**Comment by cesarzc** [comment]
Thank you for the response @chwarr!

For our schema, setting `inlineNested` to `false` in the constructor really improved initialization time while not having a measurable effect on the deserialization times themselves.

**Comment by chwarr** [comment]
Glad to hear that `inlineNested` has worked for you. This advice has helped a number of other people (via an internal-to-Microsoft discussion forum) in the past few months, so it seems like a good thing to add to the performance guidance. I've created [PR #1084, [cs] Mention inlineNested in perf guidance](https://github.com/microsoft/bond/pull/1084) to add a section about `inlineNested`.

**Comment by chwarr** [comment]
PR #1084 has been merged, but the documentation builds aren't working, so the changes haven't been published. I've opened [Issue #1086, Doc builds are not pushing to GitHub pages](https://github.com/microsoft/bond/issues/1086) for the publication problem.

I'm going to close this issue, as I believe the performance concern has been addressed.
