### ISSUE TITLE
Bond over Grpc not prepared for Grpc.Net.Client and hosting on AspNetCore?

### ISSUE THREAD

**Issue by csharper2010** [microsoft/bond#1105]
Hi,

I did my first experiments with Grpc and because I found that I liked the Bond style for defining the messages more than the feature set of Proto files, I wanted to make a Bond-over-Grpc Service. I found that compared with a Proto Grpc Service, it didn't work for me to host the Service the same way as an ordinary Protobuf Grpc Service. And on the client side, I could not use the new Grpc.Net.Client package for calling the Service. I am a complete Newbie so maybe I just don't know how it should work but I wanted to ask if Changes are planned to bring Bond-over-Grpc on par with Protobuf Grpc.

**First Problem:** I wanted to register the service implementation with 
```c#
            app.UseEndpoints(endpoints => {
                endpoints.MapGrpcService<ProtobufService>();
                endpoints.MapGrpcService<BondService>();
            });
```

Registering the BondService did not work because it seems the MapGrpcService extension method tries to register the service via the following method signature which is not generated by the Bond Grpc code generator:
```c#
public static void BindService(global::Grpc.Core.ServiceBinderBase serviceBinder, BondServiceBase serviceImpl)
```

**Second problem:** for some reason I could not get my experiment working with the Grpc.Core package and its Channel class and I tried with Grpc.Net.Client (GrpcChannel class). Using the generated ProtobufServiceClient worked fine but I could not use the BondServiceClient because its constructor requires the Channel instead of ChannelBase class from Grpc.Core.Api. Manually tweaking the generated code, I could get the client working with GrpcChannel.ForAddress("https://localhost:5001"). Is there a reason for requiring the Channel class instead of ChannelBase?

So maybe those are simply small code generation issues but there may be reasons for the way it is... some hints about that would be appreciated.

Thanks.

**Comment by chwarr** [comment]
Regarding your first problem: Bond-over-gRPC uses the [gRPC for C# (Core) library](https://github.com/grpc/grpc/tree/master/src/csharp) to host gRPC services. The `UseEndpoints` style is from the [gRPC.NET library](https://github.com/grpc/grpc-dotnet). These two libraries are not replacements for each other.

Take a look at the [Bond-over-gRPC for C# examples](https://github.com/microsoft/bond-grpc-examples/tree/master/cs) to see how to structure your clients and servers.

gRPC.NET is agnostic about the message serialization format. It has first-class support for Protocol Buffers, making it easier to use them together. If you want to use gRPC.NET with Bond messages, it will work, but it will not be as convenient as using Protocol Buffer messages.

Microsoft currently has no plans to implement Bond-over-gRPC using gRPC.NET ourselves nor any plans to add first-class Bond support to gRPC.NET. [Contributions](https://github.com/microsoft/bond/blob/master/CONTRIBUTING.md) to make Bond-over-gRPC work with gRPC.NET are welcome. If you are interested in this, please create a "discussion" issue outlining then implementation plan.

---------

For your second problem, make sure you are using gRPC.Core version 1.17.1. That is the most recent version of gRPC Core that Bond-over-gRPC has been [coded to work with](https://github.com/microsoft/bond/blob/be068e9a61eab93414538271a49f21c5074b2011/cs/src/grpc/grpc.csproj#L14). The package dependency really should be `== 1.17.1` instead of the `>= 1.17.1` that it is today. There is, however, no way to specify an exact version bound in a .csproj file.

Since 1.17.1, some of the gRPC C# abstractions were changed as part of writing gRPC.NET. This included the introduction of the `ChannelBase` class. Bond-over-gRPC was written almost two years before gRPC.NET.

Microsoft does not have any plans to update the gRPC Core version that Bond-over-gRPC uses ourselves. [Contributions](https://github.com/microsoft/bond/blob/master/CONTRIBUTING.md) to bump the gRPC Core version to something newer are welcome! A version bump contribution will be small enough that you can start with a PR if you want. No "discussion" issue needed.

**Comment by csharper2010** [comment]
Hi,

I am not experienced in the used combination of CMake and MSBuild technology and I was not successful in setting up my environment to get the set of Bond projects built.

In theory I would know what to change to enable hosting the Bond flavour of Grpc on ASP.NET Core the way it works with protobuf (using nuget package Grpc.AspNetCore) and using the Grpc.Net.Client library instead of Grpc.Core.

It would mean

- replacing the Grpc.Core package in Bond "grpc" project with Grpc.Core.Api (>= 2.23.0)
- changing the Grpc_cs.hs to use ChannelBase instead of Channel
- adding the static BindService overload public static void BindService(global::Grpc.Core.ServiceBinderBase serviceBinder, ChatClientServiceBase serviceImpl) in Grpc_cs.hs
- updating the dependencies of Grpc related example and test code to use Grpc.Core >= 2.23.0

I thing that would be a valuable change because it would bring Bond-over-Grpc up to date. It would not affect the core of Bond but only the Grpc part.

The problem is that I am unable to build the whole thing to check if everything works as expected.

**Comment by chwarr** [comment]
Feel free to open an issue with the error messages you get. We can try to help you make forward progress there.

The base of the dependencies in building gbc, so I'd make sure that you can get that working before trying to get the C# project to build. After installing the Haskell Stack tool, `cd compiler` then run `stack build`. Get that working first, then try to build `cs/cs.sln`.

**Comment by chwarr** [comment]
I believe your questions have been answered. If not, please feel free to re-open this issue with more details.
