### ISSUE TITLE
bond for client and server model generation

### ISSUE THREAD

**Issue by Yefei100** [microsoft/bond#1114]
hi,

I wonder if bond is good for my use case since I am new to bond: my client is written in c# and server in java, right now i am  writing data models in both places, and let C# first serialize the model into a json, send over Http network, and java side then deseriliaze the model from the json. So whenever I need to modify or add new models, I need to change both C# and java. I am thinking writing bond files in a central place and let it generate both C# and Java, thus reduce my work, is this feasible, and what factors should I consider when adopting bond? thanks!

**Comment by Yefei100** [comment]
Also pasted the question in StackOverflow, thanks for your suggestions.
https://stackoverflow.com/questions/68431351/microsoft-bond-for-client-and-server-model-generation

**Comment by chwarr** [comment]
Sharing data models between languages is one of the primary problems that Bond was designed to solve. That approach has been used successfully across many services inside of Microsoft. Your general approach sounds good to me.

The [Bond-over-gRPC project](https://microsoft.github.io/bond/manual/bond_over_grpc.html) takes this technique and used the gRPC transport (instead of HTTP 1.1). There's no Bond-over-gRPC for Java, so you won't be able to use Bond-over-gRPC, but you may want to look at it for inspiration.

If you have follow up questions about the finer points, feel free to ask them here.

**Comment by chwarr** [comment]
I believe this has been answered. If not, reply back. Thanks.
