### ISSUE TITLE
Data corruption in ArraySegment using unsafe deserializer

### ISSUE THREAD

**Issue by BaldMan82** [Microsoft/bond#114]
I have a strange issue with the unsafe deserializer. I'm using Bond in a project to serialize about 2000 million objects to disc. 

While running an integrity check on the data files, I have noticed that very occasionally Guid properties become corrupt (using ArraySegment). When I deserialize that peculiar byte array with a safe deserializer, the data is correct. So luckely it is not a problem in the serializer.

I have created a small test project to demo this, included a piece of problematic data as a resource byte array. Would be great if you could take a look at it.

https://drive.google.com/file/d/0B9HTQM8Ned3eMGVpYnlsVm12WDA/view?usp=sharing

**Comment by sapek** [comment]
The bug is on line 45 of `TrackingReport.cs`. You can't assume that ArraySegment has offset zero.

BTW, there is a cleaner, simpler and more performant way to use `Guid` in your Bond generated types: [custom alias type mapping](https://microsoft.github.io/bond/manual/bond_cs.html#custom-type-mappings).

**Comment by sapek** [comment]
Another comment, which is unrelated to your question, but something I've noticed in your schema definitions. You have declared many `nullable` fields. Often a better approach is to declare such fields with [default `nothing`](https://microsoft.github.io/bond/manual/bond_cpp.html#default-value-of-nothing) (we need to refactor the docs so that this info is not hidden in C++ manual, #115).

**Comment by BaldMan82** [comment]
Hi sapek, thanks for the quick reply.

I have checked the code but I'm using the ToArray() extension on the ArraySegment struct which takes in offset and count. It would also not quite explain why the unsafe deserializer code works in 99% of the cases and the safe deserializer is 100% correct on the same data piece.

In the attached demo project, only one of the 318 items in the TrackingReport_Container.TrackingReports is corrupt using the unsafe deserializer, while with the safe deserializer they are all correct. That's strange right?

I've tested the ToArray() function and it works as expected as far as I can see...

```
            var arr = new[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
            var arrSegs = new ArraySegment<int>[3];
            arrSegs[0] = new ArraySegment<int>(arr, 0, 3);
            arrSegs[1] = new ArraySegment<int>(arr, 3, 3);
            arrSegs[2] = new ArraySegment<int>(arr, 6, 3);

            Console.WriteLine("Array 1: " + string.Join(",", arrSegs[0].ToArray()));
            Console.WriteLine("Array 2: " + string.Join(",", arrSegs[1].ToArray()));
            Console.WriteLine("Array 3: " + string.Join(",", arrSegs[2].ToArray()));

            Console.ReadLine();
            
            Ouputs:
            Array 1: 0,1,2
            Array 2: 3,4,5
            Array 3: 6,7,8
```

**Comment by sapek** [comment]
You are right. I only glanced at your code and misread it as `Array`.

This is bug in `InputStream`. Thanks a lot for reporting. I'll push a fix soon.

**Comment by BaldMan82** [comment]
Can confirm this is fixed. Thanks!
