### ISSUE TITLE
Deserialization/serialization under Linux is 7x-10x slower than Windows

### ISSUE THREAD

**Issue by jiafanou** [microsoft/bond#1181]
I found the same code in Linux is almost 7x-10x slower than Windows.
I followed Linux build to get bond installed. But I used vcpkg to get bond in Windows though. 

It took ~100ms do deserialization under Windows, but 700ms-1s under Linux:

    /*
    const char* request;
    int requestSize;
    */
    bond::InputBuffer buffer(request, requestSize);
    bond::CompactBinaryReader<bond::InputBuffer> reader(buffer);
    bond::Deserialize(reader, bondRequest);

**Comment by chwarr** [comment]
That's an unexpectedly large difference. A few things I can think of to check:

1. Double check your compilation settings for you Linux build. Are you building both the Bond library and your projects with optimizations enabled, for example? My CMake is a bit rusty, but I think it defaults to a Debug build. You may want to try building the RelWithDeb or Release build type.
1. Is your benchmark taking warmup into account? C++ code doesn't need to JIT, but maybe the code needed to be loaded from disk on Linux but was already in a cache on Windows?
1. Is your benchmark running multiple iterations? What happens if you 10x the number of iterations? Does that change the per iteration timing?

**Comment by jiafanou** [comment]
Resolved by building release version. Thank you Chris.
