### ISSUE TITLE
C++: GCC: Double/Float comparison warning

### ISSUE THREAD

**Issue by sergrak** [microsoft/bond#1191]
When using double/float inside structures it's generating bad comparison (operator==) code which triggers gcc warnings
```idl
namespace Test

struct A
{
  0: required double fieldA;
  1: required float fieldB;
};
```

Run as following:
```
#:/tmp$ gbc c++ -o ./ ./test.idl
#:/tmp$ g++ -Wfloat-equal -c ./test_types.cpp
In file included from ./test_reflection.h:16,
from ./test_types.cpp:14:
./test_types.h: In member function 'bool Test::A::operator==(const Test::A&) const':
./test_types.h:59:37: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
&& (fieldA == other.fieldA)
^~~~~~
./test_types.h:60:37: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
&& (fieldB == other.fieldB);
^~~~~~
```

**Comment by chwarr** [comment]
Bond builds [with `-Wall`](https://github.com/microsoft/bond/blob/b13fee1b760119a79d038e43fb05d88e800fc7e5/cmake/Config.cmake#L158C1-L166C32). `-Wfloat-equal` is not in `-Wall`.

Please build Bond-generated code with `-Wall` and without `-Wfloat-equal`. Consider using [`-isystem` to add the generated Bond code to you header search path](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html) so that warnings are not emitted for it in your code that uses Bond. This should let you continue to use `-Wfloat-eqaul` in your own code.

The Bond project itself isn't interested in being 100% warning clean for every warning that every compiler can emit. So, we at Microsoft have no plans to change the generated code to handle `-Wfloat-equal`.
