### ISSUE TITLE
c# collections and IEnumerable

### ISSUE THREAD

**Issue by sqmgh** [Microsoft/bond#147]
Serializing the base `T` works fine.

However, if I try to serialize a `List<T>` it then returns 0 bytes.
This can be worked around by creating a very simple wrapper class, such as:
```
[Schema]
public class Wrapper<T>
{
    [ID(0)]
    public List<T> Items { get; set; }
}
```

Replacing `List<T>` with `IEnumerable<T>` throws a `The given key was not present in the dictionary.` error.

This leads to two questions:

- Is IEnumerable not supported? Needing to call `.ToList()` every time you do anything with Linq is awfully inefficient. 

- I have a hunch that not being able to serialize a `List<T>` is by design, and that you are only supposed to work with data objects, rather than lists of them. While this would be very regrettable, the user experience around it is terrible. It should then throw an exception, rather than silently eating the data you pass to it and reporting that everything is a'okay.

**Comment by chwarr** [comment]
I didn't have time to look into this today. I'll need to do so tomorrow.

**Comment by chwarr** [comment]
Your hunch about not being able to serialize `List<T>` is correct. Bond can only serialize data objects. Your wrapper is one approach. Another approach, as you can see in the test case 1 below, is to repeatedly call the same serializer with different objects and write them to the same buffer/stream. Some additional data would need to be included to indicate how many objects there are in the payload (e.g., prefixing the payload with a count or going until you encounter an `EndOfStreamException`).

I was able to reproduce the serializing `List<T>` outputting malformed payload problem. Code and output below. Really, creation of the `Serializer` for `List<Thing>` should have failed, as this isn't something that can be serialized. I've opened issue #151 for this explicitly (so that we have a smaller more targeted issue for the lack of an exception).

`IEnumerable<T>` cannot be used for any Bond collection, as when we serialize a collection, the serializer needs to know how many items there are ahead of time. (This could, perhaps, be relaxed for some protocols like XML and JSON, but it doesn't work that way today.)

The `gbc` option [`--collection-interfaces`](https://microsoft.github.io/bond/manual/bond_cs.html#code-generation) or the [`Bond.Type` attribute](https://microsoft.github.io/bond/manual/bond_cs.html#typeattribute) can be used to have fields/properties with the more generic collection interfaces like `IList<T>` (and so on), which you can back with an implementation of your choice.

```
namespace Issue147
{
    using System;
    using System.Collections.Generic;
    using Bond;
    using Bond.IO.Safe;
    using Bond.Protocols;

    internal class Program
    {
        [Schema]
        private class Thing
        {
            [Id(0)]
            public int intf;
        }

        private static void Main(string[] args)
        {
            var listOThings = new List<Thing>
                {
                    new Thing {intf = 100},
                    new Thing {intf = 200}
                };

            { // test case 1
                var output = new OutputBuffer();
                var writer = new CompactBinaryWriter<OutputBuffer>(output);

                var serializer = new Serializer<CompactBinaryWriter<OutputBuffer>>(typeof (Thing));
                serializer.Serialize(listOThings[0], writer);
                serializer.Serialize(listOThings[1], writer);

                DumpBuffer(output);
            }

            { // test case 2
                var output = new OutputBuffer();
                var writer = new CompactBinaryWriter<OutputBuffer>(output);

                var serializer = new Serializer<CompactBinaryWriter<OutputBuffer>>(listOThings.GetType());
                serializer.Serialize(listOThings, writer);

                DumpBuffer(output);
            }
        }

        private static void DumpBuffer(OutputBuffer buffer)
        {
            foreach (var b in buffer.Data)
            {
                Console.Write("{0:x}", b);
            }
            Console.WriteLine();
        }
    }
}
```

This outputs
```
10c810109030
0
```

The second test case's output makes no sense for what was asked to be serialized. As mentioned above, the creation of this `Serializer` should have failed.

Hope this helps.

**Comment by sqmgh** [comment]
Indeed it does. Thank you for the response, and creating #151.
