### ISSUE TITLE
<stdint.h> is C++11 specific

### ISSUE THREAD

**Issue by dnmiller** [Microsoft/bond#18]
I ran into this with an older compiler. I don't believe C++03 actually provides sized int types. <boost/cstdint.hpp> could be included if the compiler is not C++11.

**Comment by sapek** [comment]
We could fallback on `boost/cstdint.hpp` when the standard library header is not available (and use `BOOST_HAS_STDINT_H` to define `BOND_HAS_STDINT_H` in [config.h](https://github.com/Microsoft/bond/blob/master/cpp/inc/bond/core/config.h) for conditional include).

Since you have a repro, do you want to create a PR?

**Comment by dnmiller** [comment]
Sure, I'll put something together soon.

**Comment by ramb0x** [comment]
Has this been addressed yet?

**Comment by sapek** [comment]
No, it is still open.

**Comment by dnmiller** [comment]
Sorry for leaving this open. I ran into some compiler bugs and was unable to get a fix together. I'm fine with closing it if there's no other interest.

**Comment by sapek** [comment]
OK, closing it. Although stdint.h is technically c++11, it was available with compilers for a while. I'm open to adding a workaround if needed but I would like to do that for a specific case of a compiler/standard lib where current code doesn't work and we can verify the workaround.
