### ISSUE TITLE
Different namespace for TypeAlias converters

### ISSUE THREAD

**Issue by yagilofir** [Microsoft/bond#279]
Hi.
I am working with C#
From reading the code of this class:
https://github.com/Microsoft/bond/blob/9b8aa2fd15d72383ea86d6017c4e887c1efb8807/cs/src/core/expressions/TypeAlias.cs

I understand that in order to create a type-alias converter, my converter namespace must be the same as the namespace of the .bond scheme.
I think that this limitation is too harsh.
I want to create my own converters library with the namespace Core/Bond/Converters
Now, my DateTime converter (for example) will be Core/Bond/Converters/DateTimeConverter.cs
The MyStruct.Bond namespace does not have any relation to the namespace "Core/Bond/Converters/DateTimeConverter" (actually, it's namespace is "MyProgram/Models", But I do want it to use the converters from my core library.
Is it possible to tell the gbc.exe to use a different namespace for the type converters (other than the MyStruct.Bond namespace)?

**Comment by chwarr** [comment]
There's nothing in gbc or the C# libraries that will permit this today. Your current recourse--if you want to keep them in separate namespaces--is to have converter implementations in `MyProgam.Models` that delegate to the ones in `Core.Bond.Converters`, which can be tedious. Static classes cannot inherit from one another, so there's lots of boilerplate typing. And, you can't just move the `BondTypeAliasConverter` type into the namespace `System`, to try to get a match for `System.DateTime` as the converter must be found in the same assembly as the type.

To enable something like this, we'd need to come up with a way to annotate the C# field/property/type with the location of the converters that is used in addition/instead of the current rules. Then, we'd need to come up with a way to tell gbc to emit such an annotation. Nothing too hard, but this one should start from a design proposal, not just a code change.

**Comment by chwarr** [comment]
Having heard nothing else, closing this issue.

**Comment by eharshosh** [comment]
> To enable something like this, we'd need to come up with a way to annotate the C# field/property/type with the location of the converters that is used in addition/instead of the current rules. Then, we'd need to come up with a way to tell gbc to emit such an annotation. Nothing too hard, but this one should start from a design proposal, not just a code change.

I want to suggest a different approach to tackle the problem:
Allow specifying conversion method in a 'dependency injection' style - so that the writers/readers will look up for custom converters when it needs one.
