### ISSUE TITLE
Circular references

### ISSUE THREAD

**Issue by yallie** [Microsoft/bond#39]
Is it possible to serialize object graphs with circular references? For example,

    struct Example
    {
        0: string Name;
        1: nullable<Example> Previous;
        2: nullable<Example> Next;
    }

The code below results in StackOverflowException during serialization:

```csharp
// c# code
var first = new Example { Name = "First" };
var second = new Example { Name = "Second" };
first.Next = second;
second.Previous = first;

var output = new OutputBuffer();
var writer = new SimpleBinaryWriter<OutputBuffer>(output);
Serialize.To(writer, first);
```

**Comment by sapek** [comment]
You can defined recursive types (e.g. [generic_tree](https://github.com/Microsoft/bond/tree/master/examples/cpp/core/generic_tree)) but you can't serialize graphs with cycles. Bond type system doesn't have a concept of reference/pointer. The `nullable` type happens to be mapped to reference in `C#` but it is not same. 

In order to serialize a graph you can represent it using adjacency list, e.g. like Bond does for the built-in schema [`SchemaDef`](https://github.com/Microsoft/bond/blob/ee7f38245619e1fd690817918dcd05e05da263ab/cpp/inc/bond/core/bond.bond#L63-L120).

**Comment by yallie** [comment]
Thanks for your reply Adam. 
So there is no chance that cyclic object graphs will be supported in the future?
Too bad, that's a show stopper for me.

**Comment by sapek** [comment]
Very unlikely. Bond is not an object serialization framework. Bond type system deals with data, not objects.
