### ISSUE TITLE
How to deal with outliers in Bond code generation

### ISSUE THREAD

**Issue by aschmahmann** [microsoft/bond#396]
In converting a large set of serializable classes to use Bond I've generated a number of .bond files which in turn are generating C# code. For the most part every bond generated class has corresponding partial class that handles behavior. However, the generator has a fairly limited number of options and for a few classes it looks like my options are either change how the class works or remove the class from the .bond file and annotate the corresponding C# class manually. Are there any better options (maybe annotations in the .bond file picked up by the compiler, or allowing the compiler to ignore particular classes), or is there any thought on how this might be addressed going forward?

A couple examples:

1. Classes that aren't marked as public. The generated classes are always public so you end up with a conflicting scope error.

2. Conflicting constructors. While the default constructor is the most obvious place for a conflict it's also pretty understandable since it is presumably being used to construct the object on deserialization (since some .NET scenarios will not allow things like Activator.CreateInstance for instantiation of deserialized objects. Additionally, since no data is being passed into the constructor it can generally be worked around easily enough. However, the constructor taking two strings:
```c#
protected MyBondClass(string fullName, string name)
```
can genuinely get in the way since you might have a class that needs those two strings e.g. a Person class with fields FirstName and LastName.

**Comment by chwarr** [comment]
There's no way to have gbc ignore a struct when generating the code. You'll have to split the structs into different files, and only run codegen on one of them (but import or forward declare the other to make the names available). You can then hand-write and hand-annotate as needed.

For construction, I find myself using initialization syntax instead of constructors:

```
var Person {
    LastName = "Smith",
    FirstName = "Alice"
    // anything not mentioned gets its default value
};
```

Bond invokes the default constructor to get an object that it then inspects to determine the default values for various fields, so the default constructor is special, and care needs to be taken when implementing it.

Also worth considering: instead of adding logic to the generated Bond objects, keep them really, really, dumb, and wrap them with behavior. In some projects this makes sense. In others, not so much.

There are no specific plans for making it easier to add behavior at the moment. The Bond team's current priorities are expanding the number of languages that serialization/deserialization works in. (Going broad before going deep, if you will.)

(I was out sick; hence the delay in responding.)

**Comment by aschmahmann** [comment]
Thanks for the response and hope you're feeling better. I'll definitely consider wrapping the bond objects instead of using partial classes in the future, however I'll need to look into how I want to go about doing serialization/deserialization given that the Bond class is wrapped. Similarly, I'll likely need to decide whether it makes more sense to do custom annotation in C#, or pollute my C# namespace with public classes that really should never be used (e.g. only WrappedA should be used and not A).

Breadth over depth is pretty reasonable, however it might be helpful if there was a design document of sorts lying around. This might enable developers, like myself, who want to see specific features added, to either code generation (without touching the IDL) or the language-specific libraries, know what types of features you guys might like but don't have time to implement as opposed to features you do not feel support your goals for Bond.

Perhaps this is already covered by "enhancement" issues in Git, but this was something I was thinking about regarding a couple of the questions/issues I've recently posted.
