### ISSUE TITLE
Support for sum or union types

### ISSUE THREAD

**Issue by seagreen** [microsoft/bond#443]
Does Microsoft Bond support sum types or union types? Sorry if this isn't a good fit for a GitHub issue, but I think this will be a recurring question so it might be a good thing to address in the docs.

From my research so far it looks like there's a way to get union types [in the wire format](https://github.com/Microsoft/bond/issues/59#issuecomment-96967543), but not in the in-memory format.

**Comment by chadwalters** [comment]
We don't currently provide sum type or union support out of the box. You can use [a struct with an explicit case discriminator and optional fields](https://microsoft.github.io/bond/why_bond.html#meta-schema) to simulate it -- but this doesn't help with in-memory size or present a great programming model. As [issue 59](https://github.com/Microsoft/bond/issues/59) suggests, there are some special case approaches that can work using custom type mapping. We are looking to add more general support for unions though -- likely that work will come in summer of 2017.

**Comment by seagreen** [comment]
Interesting, thanks! That completely answers my original question.

I'm curious whether you're going to go with discriminated or non-discriminated unions. When the summer work on unions starts will there be a place I can follow it? I'm currently writing a schema system that's designed to be close to Haskell's type system, and Bond has been a massive inspiration for it (you guys do a great job with things like serializing dictionaries to JSON in a convenient way).

**Comment by chwarr** [comment]
The prototype implementation has support for F# discriminated unions. Their wire representation looks vaguely like:

```
struct bond.OneOfBase
{
    0: required uint16 case;
}

struct Foo : bond.OneOfBase
{
    0: T1 case1;
    1: T2 case2;
    ...
    n: Tn caseN;
}
```

where `OneOfBase.case` will be set to the active case ordinal, and one of the fields in `Foo` will have an "interesting" payload. The other fields will not be present at all.

This representation was chosen over having just one of the fields in `Foo` serialized so that older Bond libraries that may be intermediate proxies do not corrupt a discriminated union. They may increase the serialized payload size because they won't know that _all_ of the fields that are not the active case can be omitted. They'll just use their normal omit-default-values-if-possible logic. So, if a non-active case is a struct field, an old library would serialize an empty struct instead of omitting it.

NB: This is just a potential representation. There are still some kinks to work out, especially around `required` fields, text protocols, and untagged protocols. ***Do not expect data of this shape to be compatible with any future discriminated union support.***

I expect the discriminated union work to happen either off of a branch in the Microsoft/bond repository or in one of the primary developers forks. Not sure which, whose, or when.

**Comment by sofusmortensen** [comment]
> We don't currently provide sum type or union support out of the box. You can use [a struct with an explicit case discriminator and optional fields](https://microsoft.github.io/bond/why_bond.html#meta-schema) to simulate it -- but this doesn't help with in-memory size or present a great programming model. As [issue 59](https://github.com/Microsoft/bond/issues/59) suggests, there are some special case approaches that can work using custom type mapping. We are looking to add more general support for unions though -- likely that work will come in summer of 2017.

I guess that didn't happen... I might decide to look into this as a pastime. 

Has there been any design discussion how to do this? And if so, has it been documented anywhere?

Off the top of my head, I'd imagine simply in `.bond` doing:
```
union Foo
{
  0: bool someFlag;
  1: double someDouble;
  2: Thing someThing;
}
```
Would mean serializing it as a struct corresponding with exactly one field included (and as if that field was marked `required`).

**Comment by chwarr** [comment]
Yup, the discriminated union work never got underway. There's currently no work in progress on the front.

I dug up my notes/thoughts from November 2017, the last time I worked on this in earnest. Here they are.

-------------------------

# Oneof types (aka tagged unions, variants, discriminated unions, sum types)

The Bond type system has built-in struct types (product types), but no
built-in tagged union type. We propose adding tagged unions (sum types) and
calling them "oneof".

oneof types are generally useful, but a particular motivating example is
when implementing service methods. The return type of a service method
frequently needs to be able to distinguish between the requested data and a
rich error. For example, responding with an error that includes the type of
claim needed to perform the requested operation.

    struct CalculatorArguments
    {
        0: double left;
        1: double right;
    }

    oneof CalculatorRequest
    {
        0: CalculatorArguments add;
        1: CalculatorArguments sub;
        2: CalculatorArguments mul;
        3: CalculatorArguments div;
    }

    struct CalculatorResult
    {
        0: double result;
    }

    struct ServiceError
    {
        0: uint32 error_code;
        1: string message;
        2: string trace_id;
    }

    oneof CalculatorResponse
    {
        0: ServiceError error;
        1: CalculatorResult result;
    }

    service Calculator
    {
        CalculatorResponse Calculate(CalculatorRequest);
    }

## Simulated oneof types with today's Bond

Today, oneof types can be simulated with a case enum and a collection of
optional fields:

    enum Case
    {
        None,
        Foo,
        Bar,
        Baz
    }

    struct SimulatedOneOf
    {
        0: required Case Case = None;
        1: string Foo;
        2: int32 Bar;
        3: SomeStruct Baz;
    }

However, using such an implementation requires considerable diligence. All
consumers must explicitly know to check the Case field and then access the
corresponding field. If a mistake is made, there is no feedback, as all of
the other fields contain legal objects. Also, updating the oneof type is a
two-step process: set the Case field and then set the corresponding field.

There is serialization overhead in such an implementation, particularly in
protocols that do not omit fields, like Simple Binary. Even in a protocol
like Compact Binary, required fields will always be written, even for in
active cases.

The generated types in C++, C#, and Java take more memory, as they storage
for all of the cases at once. In C++ where the storage for many field types
is inlined in the struct itself, these types can be quite large.

## Proposal

We propose extending .bond files to include support for the `oneof` keyword.
We also discuss the serialized representation of oneof types, and how they
would be implemented in C++, C#, and Java.

### .bond files

The new `oneof` keyword can be used to define a oneof type, very much like
the `struct` keyword is used.

    struct Foo { }
    struct Bar { }

    oneof Baz
    {
        0: Foo foo1;
        1: Foo foo2; // can repeat a type
        2: Bar bar;
        3: int32 ivalue; // can use any Bond type
        4: string svalue = "default values permitted";
        7: bonded<Foo> foo3;
    }

The fields of a oneof type are identical to the fields in a struct with the
following limitations:

* Field modifiers (`required`, `required_optional`, `optional` are not
  permitted.
* The `= nothing` field default is not permitted. The active case behavior
  is conceptually similar, but they are not compatible. Nor do these two
  concepts compose well. All of the inactive cases would be nothing. But
  what does it mean for the active case to be nothing? Would it not then be
  inactive?
* `bond_meta` fields are not permitted. The `bond_meta` functionality is
  deprecated, and omitting it simplifies the design and implementation of
  oneof types.
* A oneof type may only refer to itself if its wrapped in a nullable. (This
  is the same for a regular struct, but stands repeating.)
* In a oneof, the following field names--in any casing--are reserved for the
  use of Bond:
    * which
    * unknown

Views may be created over oneof types. They are themselves oneof types with
fewer cases supported.

Oneof types may also be generic:

    oneof Quux<T1, T2>
    {
        0: T1 theFirst;
        1: T2 theSecond;
    }

Type aliases may be used for oneof types, but type converters may not. (This
  is the same for a regular struct, but stands repeating.)

### Serialized representation

A oneof type is serialized by writing only the active case.

In Compact Binary:

                      .----------.-------------------------.
     oneof (v1)       |  field   | BT_STOP or BT_STOP_BASE |...
                      '----------'-------------------------'
                      .----------.----------.-------------------------.
     oneof (v2)       |  length  |  field   | BT_STOP or BT_STOP_BASE |...
                      '----------'----------'-------------------------'
                      .----------.----------.
    field             | id+type  |  value   |
                      '----------'----------'

In Fast Binary:

                               .----------------.--------------.   .----------------.---------.
       struct/oneof hierarchy  |  struct/oneof  | BT_STOP_BASE |...|  struct/oneof  | BT_STOP |
                               '----------------'--------------'   '----------------'---------'
                         .----------.
       oneof             |  field   |
                         '----------'
                         .------.----.----------.
       field             | type | id |  value   |
                         '------'----'----------'

In Simple JSON:

    { "caseName": ... }

In Simple XML:

    <OneOfName>
        <caseName>...</caseName>
    </OneOfName>

In Simple Binary, the active case field ID is serialized before the data for
that case.

                      .---------.----------.
     oneof            |  case   |  value   |
                      '---------'----------'
     case             a uint16
     value            as otherwise in Simple Binary

Pros:

* Minimal data representation.
* Very similar to struct serialization.
* We have to do this as a forward-only change (see rejected proposals
  below), so we might as well use the simple serialized representation.

Cons:

*Need to touch bond_const.bond to add `BT_ONEOF` to `BondDataType`
    * Any existing switches on `BondDataType` will enter their `default`
      cases when encountering `BT_ONEOF`.
* An old library won't know how to process such a payload with full
  fidelity. Tagged protocols and text protocols will be able to extract some
  data and will be able to skip these fields/types.
    * An old Simple Binary reader will not know how to read or skip such
      data.
        * Looking at the current C++ implementation, it will get very
          confused when processing such a type via a SchemaDef. In
          `DynamicParser`, when an unknown field type is encountered, it
          calls `detail::BasicTypeField`. This function, in turn, will
          simply do `BOOST_ASSERT(false)` and then return `false`. However,
          `DynamicParser` doesn't inspect the return value from
          `detail::BasicTypeField`, resulting in the input reader state and
          the transform state getting out of sync. This feels like a bug
          that should be fixed.
        * The C# implementation will throw when constructing the
          deserializer. (The exception will likely be about a missing key in
          a dictionary.)

#### Rejected designs

##### Library-only

Many of the safety problems with simulated oneof types could be addressed
with a library-only solution atop an existing enum and struct. However, a
library-only solution would not solve the serialization size or memory use
problems. Additionally, gbc could not give useful diagnostics.

##### oneof as a container type instead of a top-level

Instead of having a oneof type be a top-level construct that can be
serialized like a struct, it could be more like a container type. That is,
it would be valid as a field in an existing struct, but could not be
serialized on its own.

This may be easier to implement, but it precludes oneof types being used
directly as service request/response types, necessitating an awkward
wrapping struct.

##### Pseudo-base

Conceptually, the `Baz` example from above would be serialized like the
following struct:

    struct bond::oneof_base
    {
        0: required int32 kind;
    }

    struct Baz : bond::oneof_base
    {
        0: optional Foo foo1;
        1: optional Foo foo2;
        2: optional Bar bar;
        3: optional int32 ivalue;
        7: optional bonded<Foo> foo3;
    }

where only the active field in `Baz` is actually written.

On the surface, this is compatible with old Bond libraries that don't
understand oneof types. However, when we consider untagged protocols, like
Simple Binary, this is not the case: there is no way to only serialize the
active case. Any additional metadata that we add would confuse an existing
implementation. Serializing all the cases defeats the purpose. Serializing
as a blob would work for Simple Binary, but we'd have to serialize as a blob
in all the other protocols as well to follow the SchemaDef. This would
result in two-pass serialization in protocols like Compact Binary v1.

In a SchemaDef, the fully-qualified name of the base class can be used as a
marker to check whether a given struct is a variant. There are no other
SchemaDef changes.

Pros:

* Versions of Bond before oneof support can process these payloads by
  treating them like structs with a base
    * SchemaDef-based processing will just work.
    * For codegen-based processing, a hand-written struct that matches the
      pseudo-struct will be needed.
* A oneof type is indicated by a "magic" base type name.

Cons:

* There's duplicated information between the kind field in the base and
  which serialized variant is present.
* A oneof type is indicated by a "magic" base type name.
* Not actually compatible with Simple Binary.

## Implementation sketches

### C++ implementation

We will generate code like the following:

    class Baz
    {
    public:
        struct Which
        {
            enum class Id : uint32_t
            {
                foo1 = 0;
                foo2 = 1;
                bar = 2;
                ivalue = 3;
                svalue = 4;
                foo3 = 7;
                unknown = 65536;
            };

            struct foo1_tag_t { } foo1;
            ...
            struct foo3_tag_t { } foo3;
        };

        Baz(); // which() == foo1, and a Foo was default constructed
        // also allocator ctors

        Baz(const Baz&) noexcept(...);
        Baz(Baz&&) noexcept(...);

        template <typename T...>
        explicit Baz(Which::foo1_tag_t, T...& args)
        {
            // changes which to foo1
            // forwards to Foo ctor
        }
        ...
        
        // only way to create a oneof in the unknown state
        explicit Baz(bond::oneof::unknown_tag_t);
        ...

        int32_t which() const noexcept;

        const Foo& foo1() const noexcept; // only valid to call if which() == foo1
        Foo& foo1() noexcept /*?*/; // changes which() to foo1
 
        template <typename T...>
        void emplace(foo1_tag_t, T&&...);
        ...

        Baz& operator=(const Baz&) noexcept(...);
        Baz& operator=(Baz&&) noexcept(...);

        struct Schema
        {
            public: class var
            {
                ...
                // do we need this, or just the compile time visit API?
                using struct : ::bond::reflection::FieldTemplate<...> which;
            }
        }
    }

There will need to be a compile-time visit API.

In a C++ oneof, some case is always active, even if that case is the unknown
case. A oneof in the unknown case cannot be serialized: attempting to do so
will result in a runtime exception. When merging oneof types, if the source
is unknown, then the payload's value is taken.

When the default ctor for a C++ oneof is run, it will be created in the case
of its lowest numbered field.

OPEN QUESTION: if exceptions are thrown, will the oneof transition to
unknown? (Cf. `std::variant` which throws if you attempt to access after an
exception, and `boost::variant`, which goes through tons of effort to never
be empty.)

Since the only extra member function is `which()`, which is already
reserved, there is no possibility for name clashes.

This can be implemented using something like `bond::detail::any` or perhaps
`boost::variant`. We cannot use `std::variant` as we still only target
C++11. Such an implementation only has one allocation: as a trade-off the
resulting type is as large as its largest member, even if that member is not
active.

Since oneof types are top-level serializable objects, there is no need to
handle type converters. Thus a "oneof concept" is not needed.

If needed, oneof types can be MSVC 2015 and later only.

#### More fleshed out C++ APIs:

    /**
    
       oneof Baz {
       0: Foo foo1;
       1: Foo foo2; // can repeat a type
       2: Bar bar;
       3: int32 ivalue; // can use any Bond type
       4: string svalue = "default values permitted";
       7: bonded<Foo> foo3;
       }
    
    **/
    
    class Baz
    {
    public:
        struct Which
        {
            enum class Id : uint32_t
            {
                foo1 = 0;
                foo2 = 1;
                bar = 2;
                ivalue = 3;
                svalue = 4;
                foo3 = 7;
                unknown = 65536;
            };
    
            struct foo1_tag_t {
                using type = Foo;
                static constexpr Id id = foo1;
            } foo1;
            ...
            struct foo3_tag_t { } foo3;
        };
    
        Baz(); // which() == unknown
        // also allocator ctors
    
        Baz(const Baz&) noexcept(...);
        Baz(Baz&&) noexcept(...);
    
        Which::Id int32_t which() const noexcept;
    
        const Foo& foo1() const noexcept
        {
            BOOST_ASSERT(_active == Which::Id::foo1);
            return boost::get<0>(_storage);
        }
    
        Foo& foo1() noexcept; // only valid if which == foo1
    
        Baz& operator=(const Baz&) noexcept(...);
        Baz& operator=(Baz&&) noexcept(...);
    
        struct Schema
        {
        public: class var
                {
                    static constexpr bool is_oneof = true;
                    ...
                    // do we need this, or just the compile time visit API?
                    using struct : ::bond::reflection::FieldTemplate<...> which;
        }
        }
    
        template <typename F>
        friend decltype(auto) visit(Baz& b, Which:Id id, F f)
        {
            switch (id)
            {
                case Which::Id::foo1:
                    return f(b.foo1());
                    //...
                default:
            }
        }
    
    private:
        bond::variant<Foo, Bar, int32_t, std::string, bond::bonded<Foo>> _guts;
    }
    
    template <typename Ts...>
    class variant
    {
    
    };
    
    //bond::oneof::get(myBaz, Baz::foo1);
    //bond::oneof::emplace(myBaz, Baz::foo1, ...);
    bond::oneof::visit(myBaz, visitor);
    
    class Visitor
    {
        void operator()(Baz::foo1_t, Foo& f) { /* use f */ };
        ...
    };
    
    
    baz.foo()->access_field;
    baz.foo() = something;
    
    template <typename OOType, typename CaseTag>
    struct OneOfCaseProxy
    {
        const CaseTag::Type& operator->() const noexcept;
        CaseTag::Type operator->() noexcept;
    
        CaseTag::Type& operator=(const CaseTag::Type&);
        CaseTag::Type& operator=(CaseTag::Type&&);
    
        template <typename... T>
        CaseTag::Type& emplace(T&&...);
    
        // returns true if which == CaseTag::id
        explicit operator bool() const noexcept;
    
        // ub if not right case
        const CaseTag::Type& get() const noexcept;
        CaseTag::Type& get() noexcept;
    }
    
    
    deserialization:
    
    read which
    bond::oneof::get(theThingBeingDeserialized,
    Deserialize(bond::oneof::get(...));


#### Rejected proposals

Directly using something like `boost::variant` has too many drawbacks:

* Ties us to their API, which can change without our knowledge.
* `boost::variant` is more type-focused, and there's place for the
  human-usable names.

-------

Instead of prefixing all of the member functions with something to avoid
clashes, we could use a collection of free functions:

    template <typename T>
    T::Which bond::oneof::which(const T& oo) noexcept;

    // these return nullptr is not the specificed case
    template<typename WhichT, typename T>
    const WhichT::type* bond::oneof::get(const T& oo) noexcept;
    
    template<typename WhichT, typename T>
    WhichT::type* bond::oneof::get(T& oo) noexcept;



    use:
    
    Foo f = bond::oneof::get<Baz::WhichT::foo1>(myBaz); // template spec.
    Foo f = bond::oneof::get(Baz::WhichT::foo1, myBaz); // overloads
-------

Type converters are not supported for oneof types, so a "oneof concept" is
not needed. For a sketch of the "oneof concept", see the free functions,
above.

### C\# implementation

We will generate code like the following:

    [Bond.OneOf]
    class Baz
    {
        public enum Which
        {
            foo1 = 0;
            foo2 = 1;
            bar = 2;
            ivalue = 3;
            foo3 = 7;
            Unknown = 65536;
        }

        Baz(); // Which == foo1, and a Foo was default constructed
        
        // Only way to create a oneof in unknown.
        Baz(Bond.OneOf.Unknown);
        
        // throws if the which and the type of the value don't align
        Baz(Which which, Foo value);
        Baz(Which which, Bar value);
        Baz(Which which, int32 value);
        Baz(Which which, IBonded<Foo> value);

        Which Which { get; }

        // throws if Which != foo1
        // set changes Which to foo1
        [Bond.Id(0)]
        Foo& foo1 { get; set; }
    }

The implementation will likely be just a `Which` field and an `object`
field.

Since the only extra member function is `Which`, which is already reserved,
there is no possibility for name clashes.

When the default ctor for a C# oneof is run, it will be created in the case
of its lowest numbered field.

An attribute `Bond.OneOf` is used to indicate a class/struct/interface that
is a oneof type. These must have a property of an enum type named `Which`.
Then, each of the fields/properties annotated with `Bond.Id` are the cases.

A oneof in the `Unknown` case cannot be serialized: attempting to do so will
result in a runtime exception.

When Merge is implemented, then preservation of unknown oneof values can be
enabled.

### Java implementation

Likely very similar to the C# implementation.

We'd need setters, so everything would need to be prefixed to avoid clashes.

**Comment by sofusmortensen** [comment]
thanks @chwarr 

This is exactly how I had imagined compact binary serialization of unions and mostly how I imagined doing the C# mapping. Hadn't given other formats or mapping much thought.

I wonder if I were to push forward getting this implemented for compact binary and C# what would the chances be of either:

- Bond maintainers helping out completing the PR for the full coverage
- the PR supporting only C#, maybe C++, and compact rep being merged to master

**Comment by chwarr** [comment]
Thanks for the offer, but this isn't something that we're currently interested in adding to Bond.

**Comment by computerquip** [comment]
This seems like a fairly important feature to not have any interest in adding.

**Comment by chwarr** [comment]
Thanks for your interest in oneof. Briefly, oneof isn't something that we need at Microsoft, so we don't have any plans to implement it. If this lack is a deal-breaker for you, there are other binary serialization formats that do support the oneof concept, like Avro, Cap'n Proto, Protocol Buffers, or Thrift.

Inside of Microsoft, we're been [ok using inheritance](https://github.com/microsoft/bond/tree/master/examples/cs/core/polymorphic_container) to model the exclusiveness of types that oneof would also allow modeling. C++, C#, and Java--the primary languages that Bond is used in--don't have native support for oneof types either. Thus, adding explicit oneof support isn't something that we, Microsoft, plan to add to Bond for the foreseeable future.

Also, given its complexity, it's also not something that we're comfortable adding in a piecemeal fashion as [sofusmortensen volunteered to do](https://github.com/microsoft/bond/issues/443#issuecomment-582802775). Something that changes the Bond type system this way needs to be implemented in all the supported protocols and languages. If someone is interested in that, feel free to comment here. It's a large amount of work to undertake.
