### ISSUE TITLE
C# - Transcode Without Schema Issues

### ISSUE THREAD

**Issue by charles-griffith** [Microsoft/bond#445]
I am serializing a simple C# object using the CompactBinaryWriter. When attempting to Transcode this serialized object to XML, a null object reference exception is thrown. Any assistance would be appreciated. 

Thank you
Charles
(Please excuse the messy code) 
[Program.txt](https://github.com/Microsoft/bond/files/994139/Program.txt)
[Thing.Bond.txt](https://github.com/Microsoft/bond/files/994148/Thing.Bond.txt)

```
Object reference not set to an instance of an object.
   at lambda_method(Closure , CompactBinaryReader`1 , SimpleXmlWriter )
   at Bond.Transcoder`2.TranscoderHelper.Transcode(R reader, W writer) in C:\src\nuget\bond\cs\src\core\Transcoder.cs:line 156
   at Bond.Transcode.FromTo[R,W](R reader, W writer) in C:\src\nuget\bond\cs\src\core\Transcoder.cs:line 33
   at BondSerialization.Program.Main(String[] args) in C:\Users\cgriffith\Desktop\BondSerialization\BondSerialization\Program.cs:line 46
```

**Comment by chwarr** [comment]
To transcode to a text-based protocol, a schema (either a static schema from the type or a runtime schema) is required. The text protocols need schemas so they know which field name to use for a given field id. The `NullReferenceException` is arising due to the lack of a schema to provide metadata for each field.

The [protocol transcoding example](https://github.com/Microsoft/bond/blob/bcabcd0aac1c2a4d5bf3015519f8a568caec26ed/examples/cs/core/protocol_transcoding/program.cs#L36) uses a static/compile-time schema. To use a runtime schema, you can [construct a `Transcoder`](https://github.com/Microsoft/bond/blob/bcabcd0aac1c2a4d5bf3015519f8a568caec26ed/cs/src/core/Transcoder.cs#L89-L93) with a `RuntimeSchema` instance.

Yes, the error message could be better.

**Comment by chwarr** [comment]
Closing for now. Please re-open if needed.
