### ISSUE TITLE
Release packages doesn't include third-party libraries

### ISSUE THREAD

**Issue by eharshosh** [Microsoft/bond#518]
Hi,

After downloading a release package, I've noticed that the sub-folders under the `thirdparty` folder are empty.
Is this by design or a bug? they are needed for building the product...

**Comment by chadwalters** [comment]
When you say "downloading release package", do you mean the NuGet packages?

If you are referring to cloning the repo at the tagged release, did you include the `--recursive` flag when you did `git clone`?

**Comment by eharshosh** [comment]
I meant downloading a zip file from the 'Releases' page.. e.g. https://github.com/Microsoft/bond/archive/6.0.0.zip

**Comment by chadwalters** [comment]
I see. We'll look into the best way to deal with the various thirdparty submodules in the releases.

Since the "releases" you are interested in are just source code, the recommended approach for now would be to `git clone --recursive` and then checkout the tag for the release you are interested in (e.g.: `git checkout 6.0.0`).

**Comment by chwarr** [comment]
I don't see any way to control the contents of the archives on the release page. They are produced by GitHub automatically from the Git tag for the release, and seem to be the moral equivalent of running `git archive`, which has no support for embedding submodules. So, as @chadwalters mentioned, you'll need to recursively clone the repositories to get all the code needed.

**Comment by chwarr** [comment]
Please let us know if you have follow up questions. Closing for now.
