### ISSUE TITLE
Array Collection

### ISSUE THREAD

**Issue by grant-d** [Microsoft/bond#60]
Is it possible to get a true array `Foo[]` collection in generated C#, as opposed to `List<Foo>`?

**Comment by grant-d** [comment]
I found a solution that compiles, but not sure if this is supported.
Please let me know if this looks OK?

    using CacheBlits = blob;
    struct CacheBlitRow
    {
        0: optional CacheBlits Blits = nothing;
    }

Note the array**[]** specifier on the singular form in the .csproj alias:

    --using "CacheBlits=<namespace>.CacheBlit[]"

Code-gen looks like this (and since I used `=nothing` the default .ctor does not try to init the array)

    [global::Bond.Id(0), global::Bond.Type(typeof(global::Bond.Tag.blob))]
    public <namespace>.CacheBlit[] Blits { get; private set; }

And finally the converter:

     public static CacheBlit[] Convert(ArraySegment<Byte> value, CacheBlit[] unused)
     { ... }

**Comment by sapek** [comment]
Yes, you can [alias list/vector\<T\>](https://github.com/Microsoft/bond/blob/1c9e96f03492ff1e385cc607edcba4f8015ec086/cs/test/core/Aliases.bond#L7) to [T[] in C#](https://github.com/Microsoft/bond/blob/1c9e96f03492ff1e385cc607edcba4f8015ec086/cs/test/core/Core.csproj#L54). The trick, as you've discovered, is to set the default value to `nothing` because array construction syntax in C# is irregular and there is no special case for this in the codegen (it is just using general purpose type alias mapping facilities).
