### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by zapov** [Microsoft/bond#63]
Hi guys,

do you have any reference benchmarks? I was unable to find any ;(
I tried Bond for C# and fast binary was not really fast (usually 2-3 times slower than JSON - which I would assume is really the speed of Newtonsoft).

Also is there a better API than Bond.Deserialize&lt;T&gt;.From(reader)
something like Bond.Deserialize.From(reader, type) ?

**Comment by sapek** [comment]
We do have benchmark we use internally to track performance although we have decided to not open source them (at least for now). As you know benchmarks are a can of worms - if you try hard enough you can prove anything. That's why I would much prefer if a third party provided benchmarks for Bond than us. I'm aware of one such [comparison to protobuf.net](https://github.com/takemyoxygen/bond-performance-tests), albeit limited, which more or or less aligns with our internal results (C# Bond is 2-4 times faster depending on schema) than protobuf.net.

FastBinary being slower than JSON definitely sounds wrong. It should be about an order of magnitude faster. You can find some discussion of [performance in Bond docs](https://microsoft.github.io/bond/manual/bond_cs.html#performance). I would also be happy to take a look at your benchmark code if it is on GitHub.

**Comment by zapov** [comment]
I wouldn't go that far and compare benchmarks to statistics. I always appreciate well done benchmarks. Even if codecs differ from use case to use case.

Anyway, I've pushed the initial version to my bench and here is where I set up bond: https://github.com/ngs-doo/json-benchmark/blob/master/Benchmark/Program.cs#L398

Not sure what I'm doing, but the numbers don't look good ;(
BondJson: 18598 / 46177 / error
BondBinary: 41032 / 47315 / 56397

for comparison:
Jil: 11703 / 15299 / 38717
Protobuf.NET: 7444 / 6796 / 31940
Revenj (JSON): 6348 / 10054 / 20339

Also, not sure how to go about few things ;(
For example I want to use Guid, DateTime (Date actually) and decimal. They don't look good in JSON as currently defined in shema. I can always convert them to String I guess, but that would kind of defeat the purpose.

Regards,
Rikard

**Comment by sapek** [comment]
By default Bond pre-allocates a buffer of 64KB for its input/output streams. That might be a good default for a large application but definitely is too big for a benchmark testing with tiny objects. We end up measuring cost of memset :-).

The fix is trivial. I send you a [PR](/ngs-doo/json-benchmark/pull/4).

BTW, when de/serializing from/to memory, you can even better performance with Bond using `ArraySegment<byte>` rather than streams. See the [Performance section](https://microsoft.github.io/bond/manual/bond_cs.html#performance) in the docs for more details.

**Comment by sapek** [comment]
Regarding your other question about Guid/Date/Decimal: these are handled in Bond via [type alias](https://microsoft.github.io/bond/manual/compiler.html#type-aliases) feature. You can choose which of the built-in types you want to alias. For instance, in the [example](https://github.com/Microsoft/bond/blob/95b81030837c53028b69a4629c2627922f96af96/examples/cs/core/date_time/schema.bond#L3) we represent `DateTime` as `int64` but you could as well define it as an alias of `string` and define appropriate [conversion](https://github.com/Microsoft/bond/blob/95b81030837c53028b69a4629c2627922f96af96/examples/cs/core/date_time/program.cs#L11-L19) routines.

**Comment by zapov** [comment]
Tnx, that fixes the problem with my bench. Although don't look like a good general solution, since other tests will use larger payload.
Now Bond really is faster than Revenj and Protobuf, although only from slightly faster to up to 50% faster.

I did use type aliases from your example, but as I said they were serialized strangely in JSON. I'll look into using string instead (but I suspect decimal will be quoted - which is not really correct).

I avoided ArraySegment since that would require me to either limit the amount of ram per thread/context or still leak memory ;(

Ah, now I have an excuse to improve Revenj speed ;(
