### ISSUE TITLE
Build error when adding u16string type alias

### ISSUE THREAD

**Issue by nathpete-msft** [Microsoft/bond#637]
I'm using Bond in an Android project, and when trying to a type alias for `u16string` it fails to build with the following error. The Bond piece is implemented as a separate CMake library that's included in my main native lib, and there's a stripped down example of how I have this set up below.

```
In file included from C:\Projects\sampleApp\.externalNativeBuild\cmake\debug\armeabi-v7a\sample\bond\gen\data_apply.cpp:2:
In file included from sample/bond/gen/data_apply.h:5:
In file included from ../lib/bond/inc\bond/core/bond.h:7:
In file included from ../lib/bond/inc\bond/core/apply.h:9:
In file included from ../lib/bond/inc\bond/core/parser.h:9:
In file included from ../lib/bond/inc\bond/core/transforms.h:11:
../lib/bond/inc\bond/core/detail/omit_default.h:62:50: error: no matching member function for call to 'compare'
    return !metadata.default_value.wstring_value.compare(0, std::wstring::npos, string_data(value), string_length(value));
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

**u16string.h**:
```
#pragma once

#include <cassert>
#include <bond/core/container_interface.h>

namespace bond
{

template <> struct
is_wstring<std::u16string> : true_type {};

inline const char16_t* string_data(const std::u16string& str)
{
    return str.data();
}

inline char16_t* string_data(std::u16string&)
{
    assert(false);
    return 0;
}

inline uint32_t string_length(const std::u16string& str)
{
    return static_cast<uint32_t>(str.length());
}

inline void resize_string(std::u16string& str, uint32_t size)
{
    str.resize(static_cast<size_t>(size));
}

} // bond
```

**data.bond**:
```
namespace sample.data;

using u16string = wstring;

struct Data
{
    0: u16string value
}
```

**CMakeLists.txt**
```
include(Bond)

find_program(GBC_PATH NAMES "gbc" PATHS "${PROJ_ROOT}/lib/bond/bin/win32")
set(BOND_GBC_PATH ${GBC_PATH})

add_bond_codegen(${PROJ_ROOT}/bond/data.bond
                 OUTPUT_DIR ${PROJ_ROOT}/bond/gen
                 IMPORT_DIR ${PROJ_ROOT}/bond/inc
                 OPTIONS --header=\"<u16string.h>\" --using=\"u16string=std::u16string\"
                 TARGET BOND_OUT)
set(sources
     ${PROJ_ROOT}/bond/gen/data_types.cpp
     ${PROJ_ROOT}/bond/gen/data_apply.cpp)

add_library(bond_data ${sources})

target_include_directories(bond_data
    PUBLIC
        ${PROJ_ROOT}/bond/gen)

target_include_directories(bond_data
    SYSTEM
    PUBLIC
        ${PROJ_ROOT}/lib/boost
        ${PROJ_ROOT}/lib/bond/inc)

add_dependencies(bond_data BOND_OUT)
```

**Comment by chwarr** [comment]
Possibly related: https://github.com/Microsoft/bond/issues/143

**Comment by chwarr** [comment]
One thing that's I see that's odd is that the `is_string` specialization of `is_default` was picked, not the `is_wstring` one... Let's say we resolve that, what's your platform's underlying char implementation of `std::wstring`? If `std::wstring` and `std::u16string` don't have compatible char types, we may need to look at figuring out how to hook conversions into the string concept as well...

**Comment by nathpete-msft** [comment]
Ah, yeah, I accidentally copied the details up from one of my builds using `string` rather than `wstring`, but my actual attempt using `wstring` resulted in the same build errors.

Android is built on Linux, so `wchar_t` is 4 bytes. Does mean the only real option would be to add `u16string` as a native Bond type variant, and update `stl_containers.h` accordingly?

**Comment by chwarr** [comment]
I'm not quite sure what you mean when you say "native Bond type variant". I don't see adding a third string type of the Bond type system on par with string and wstring as a viable solution, if that's what you intended. (The third string type to add to the Bond type system would be more like wwstring for UTF32 encoded data. [string is UTF8 encoded and wstring is UTF16 encoded. {C++ doesn't enforce this, but the other languages do.}])

This particular compiler error is when, during serialization, the check against the field's default value is performed. It's attempting to compare a `std::wstring` aka `std::basic_string<wchar_t>` with a string delimited by two `char16_t*` from your implementation of `string_data`. `wchar_t` != `char16_t` for you, so there's no matching overload of `std::wstring::compare` found.

Where did this `std::wstring` come from? Since the underlying Bond type of the custom string is a `wstring`, it's default value (from say a line like `0: u16string someField = "the default value"` in a .bond file) is stored as a `std::wstring`.

Auditing the code, there are a few other places where it has assumed that something that is `is_wstring` uses `wchar_t`, like in the [Simple JSON writer](https://github.com/Microsoft/bond/blob/5454d52ea0b55ee696e1bd2727d5492379abe06f/cpp/inc/bond/protocol/simple_json_writer.h#L160)

The library already has some code to handle differing character widths, like the [`string_char_int_type`](https://github.com/Microsoft/bond/blob/11beaf5319639e4bdee96a25f95154e4fed93a75/cpp/inc/bond/protocol/encoding.h#L158-L171) in encodings.h. The short term fix may simply be to perform the comparison after using the reverse transformation of what encodings.h does...

@ara-ayvazyan: anything you see or want to add here?

**Comment by DHowett-MSFT** [comment]
I think the core issue is that _Bond_ (+Windows) sees `wstring` as UTF-16, but Linux, iOS, Android, and a bunch of other post-standardization platforms don't agree with that definition. Since Bond means UTF-16, that projects most portably in C++ as `u16string`. It's not a request to add a new string type, but to support ingesting (C++-side) `u16string` and forcing them through Bond's "narrow to UTF-16" transcoder. Right now it's ingesting a UTF-32 string and narrowing it to UTF-16 (and in doing so truncate codepoints > `0xFFFF`).

I guess that means it's a request for concision and the ability to say "your UTF-16 string is my UTF-16 string" and get everyone on the same page.

**Comment by chwarr** [comment]
Agreed that `std::u16string` is the more natural C++ type (Insert rant about how `span<byte>` might be the most natural type. 😄). #143 is a bit easier now that Bond requires a C++11 compiler and STL (that wasn't the case when #143 was opened), as `std::u16string` and `char16_t` will exist everywhere now. (Though, as usual MSVC 2013 is a problem. It doesn't appear to have `char16_t`...)

I added a summary of the problems uncovered in this issue to #143.

Would adding this functionality be something that either of you are interested in contributing, @nathpete-msft or @DHowett-MSFT?
