### ISSUE TITLE
undefined reference in inheritance.h in debug mode

### ISSUE THREAD

**Issue by FDUdannychen** [Microsoft/bond#735]
Learning from the example, my code looks like:
```
void DoSomething(
            bond::ext::gRPC::unary_call<
                bond::bonded<MyRequest>,
                bond::Void> call) override
        {
            auto request = call.request().Deserialize();
            //...
            call.Finish(bond::Void());
        }
```
When my project is compiled in Debug mode:

> cmake -DCMAKE_BUILD_TYPE=Debug

I will get error messages when `make`:
```
CMakeFiles/server.dir/host/server.cpp.o: In function `_ZN4bond6detail17ParserInheritanceIRNS_19CompactBinaryReaderINS_11InputBufferEEENS_13DynamicParserIS5_EEE4ReadINS_4Void6SchemaENS_10SerializerINS_19CompactBinaryWriterINS_20CompactBinaryCounter4typeEEENS_16BuiltInProtocolsEEEEEN5boost12disable_if_cIXgtsr15hierarchy_depthIT_EE5valuesr14expected_depthIT0_EE5valueEbE4typeERKSL_RKSM_':
/usr/local/include/bond/core/detail/inheritance.h:99: undefined reference to `bond::Void::Schema::metadata'
```
Switching between Clang3.8 and GNU5.4 will not help. But everything is working fine in Release mode:

> cmake -DCMAKE_BUILD_TYPE=Release          //or simply cmake without the build type arg

Am I missing something?

**Comment by ara-ayvazyan** [comment]
From the error message it seems like you're missing a dependency on `bond` static library?

**Comment by FDUdannychen** [comment]
@ara-ayvazyan But it's working in release mode. I don't see any dependency difference between debug and release.

**Comment by chwarr** [comment]
It looks like the generated _grpc.h header may be missing a `#include <bond/core/bond_reflection.h>` when events or no-argument functions are being used.

Potential work around: add this before your include of the relevant generated _grpc.h headers:

```
#include <bond/core/bond_reflection.h>
```

After including this header your executable will have a dependency on libbond.a/bond.lib. That's where the metadata for types like `bond::Void` is compiled.

As for why it works in release but not in debug, that could be due to the optimizer determining that some section of code/template doesn't actually get executed/expanded and skipping it. There's one `NDEBUG` in the codebase (in [value.h:851](https://github.com/Microsoft/bond/blob/46527ce7dfa2fcab384751fbfa0bc852bb5524bf/cpp/inc/bond/core/value.h#L852)), but it doesn't look relevant here.

**Comment by chwarr** [comment]
Can you try my [proposed improvement](https://github.com/Microsoft/bond/pull/738)?
This may improve the error message, but linking with libbond.a would still be required.

It's in the branch [chwarr/grpc-include-reflection](https://github.com/chwarr/bond/tree/chwarr/grpc-include-reflection) of my fork of Bond: https://github.com/chwarr/bond.git:

```
git checkout -b chwarr/grpc-include-reflection master
git pull https://github.com/chwarr/bond.git chwarr/grpc-include-reflection
```

**Comment by FDUdannychen** [comment]
@chwarr Your PR fixes the issue. Thanks.

**Comment by chwarr** [comment]
Really, it fixes the issue completely? Hrm... I was just expecting a more informative compiler error.

Can you share the linker command line that was invoked when you built with my proposed fix? (I'm trying to see whether or not libbond.a was linked in. If it was linked in, that's what I expect is the real fix. If it wasn't linked in and this still fixed it, something else is going on that I want to dig into.)
