### ISSUE TITLE
bond.dll public key token changed

### ISSUE THREAD

**Issue by koote** [Microsoft/bond#783]
Hi, I occasionally upgraded Bond.Runtime.CSharp from 3.0.7 to latest 7.0.1, I found that Bond.dll public key token changed, it makes assembly binding redirect doesn't work. Any workaround except I have to stay on 3.0.7 (bond.dll v1.0.0.0) ? Why public key got changed? Thanks.

**Comment by chwarr** [comment]
This was an intentional breaking change between 5.x and 6.x to enable people outside of Microsoft to build and use strong-named signed Bond assemblies.

From the [changelog](https://github.com/Microsoft/bond/blob/master/CHANGELOG.md#600-2017-06-29):

> 
> * **Breaking change** Bond assemblies are now [strong-name signed](https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx) with the
>   [bond.snk](https://github.com/Microsoft/bond/blob/82c97e12621eeb906d1bd46e3abba9da14289c61/cs/build/internal/bond.snk) key in the repository instead of with a Microsoft key. This allows anyone to produce compatible assemblies, not just Microsoft. Official distribution of Bond will continue to be [Authenticode signed](https://msdn.microsoft.com/en-us/library/ms537361(v=vs.85).aspx) with a Microsoft certificate. [Issue #414](https://github.com/Microsoft/bond/issues/414)
>     * The new public key for assemblies is now `00240000048000009400000006020000002400005253413100040000010001000d504ac18b4b149d2f7b0059b482f9b6d44d39059e6a96ff0a2a52678b5cfd8567cc67254132cd2debb5b95f6a1206a15c6f8ddac137c6c3ef4995f28c359acaa683a90995c8f08df7ce0aaa8836d331a344a514c443f112f80bf2ebed40ccb32d7df63c09b0d7bef80aecdc23ec200a458d4f8bafbcdeb9bf5ba111fbbd4787`
> * **Breaking change** Bond assemblies now have assembly and file versions that correspond to their NuGet package version. Strong name identities will now change release-over-release in line with the NuGet package versions. [Issue #325](https://github.com/Microsoft/bond/issues/325)

From issue #414, emphasis added:

> 
> Currently, when you build Bond locally, it uses bond.snk to sign the .NET assemblies. However, when an official release of Bond is produced, a Microsoft-internal key is used to sign the assemblies. This means that locally produced assemblies and Microsoft-produced assemblies have different strong names. The *current guidance for Microsoft open source projects is to use one key that is accessible to everyone for strong name signing*, and to Authenticode sign official Microsoft releases for integrity. (Official release of Bond are already Authenticode.)
> 
> This will be a breaking change, as it will change the strong name of the assemblies.

Version 3.0.7 is 13 versions behind and over two years old, so I urge you to consider upgrade the things still consuming version 3.0.7 to 7.0.1. I understand that you may not be in a position to do this, depending on where these dependencies are coming from. Version 5.3.1 is the most recent version with the old strong name. (If you need help convincing other teams at Microsoft to upgrade their packages, please feel free to enlist me.)

The breaking changes between versions 3.0.7 and 7.0.1 are captured in the [changelog](https://github.com/Microsoft/bond/blob/master/CHANGELOG.md). They're all what I'd call "minor breaking changes", but since we use [SemVer](https://semver.org/), we incremented the major version. If you run into problems handling the changes, feel free to open an issue.

**Comment by koote** [comment]
Thanks, I am internal Microsoft user and Bond.dll v1.0.0.0 is referenced by Microsoft.Azure.Monitoring.DataPipe.Blob.IO.dll, Microsoft.Azure.Monitoring.DataPipe.Blob.IO.Search.dll. I cannot use assembly redirect because of public key change.

**Comment by chwarr** [comment]
Since this is about Microsoft internal packages, let's continue this conversation elsewhere. Can you e-mail me with these details?

**Comment by chwarr** [comment]
@koote: I haven't seen an e-mail with details, so I'm going to close this issue for now.
