### ISSUE TITLE
Is there a Union type in bond

### ISSUE THREAD

**Issue by NYProgrammer** [Microsoft/bond#799]
I have an issue where I need to send following object across the wire - 
```
struct RemoteObjectWrapper:BaseObject
{
    0: int32 ServiceAdapterId;
    1: int32 MethodId;
	2: bonded<BaseObject> InnerObject;
}
```
where BaseObject is an empty struct ( similar to Void)

I want to stuff any datatype in the Innerobject...
It is perfect for data types like our structs like - 
```
struct SomeObject: BaseObject
{
	0: string Name;
	1: int32 Id;
}
```

However, I am writing some framework code where I want to do something like this - 
```
private static byte[] CreateRemoteWrapperBytes<T>(ISerializerDeserializer bond, dynamic innerObjectValue) where T : BaseObject, new()
        {
            dynamic methodParamObject = new T();
            methodParamObject.InnerObject = innerObjectValue;
            RemoteObjectWrapper remoteCallWrapperObject = new RemoteObjectWrapper()
            {
                InnerObject = new Bonded<T>(methodParamObject),
                ServiceAdapterId = new Random().Next(100),
                MethodId = new Random().Next(100)
            };
            //need to serialize this object now...
            byte[] remoteObjectInBytes = bond.Serialize(remoteCallWrapperObject);
            return remoteObjectInBytes;
        }

```
and 
```
public static T UnWrapBytesAndPrint<T>(ISerializerDeserializer bond, byte[] packedBits) where T : BaseObject
        {

            // Pass this to another class/function and deserialize there...
            RemoteObjectWrapper ro = bond.DeSerialize<RemoteObjectWrapper>(packedBits);
            WriteLine($"-Deserialized:\n\t-RemoteWrapper Object Info :Adapter: {ro.ServiceAdapterId} , MethodId: {ro.MethodId}");
            BaseObject baseObjec = ro.InnerObject.Deserialize();
            var bondedMessageParam = ro.InnerObject.Convert<T>();
            dynamic unwrappedMessageParam = bondedMessageParam.Deserialize();
            WriteLine($"\t-InnerObject(MessageParam) Object Info : {unwrappedMessageParam.InnerObject}");
            return unwrappedMessageParam;
        }

```
The only way for me to make this work is by having something like this in bond file for each datatype...
I could solve this if we had a union in bond.. 

```
struct iLinkedList<T>	:BaseObject	{	0:list<T>		InnerObject;		}
struct iList<T>			:BaseObject	{	0:vector<T>		InnerObject;		}
struct iNullable<T>		:BaseObject {	0:nullable<T>	InnerObject;		}
struct iMap<K,T>		:BaseObject	{	0:map<K,T>		InnerObject;		}
struct iSet<T>			:BaseObject	{	0:set<T>		InnerObject;		}
struct iByte			:BaseObject	{	0:uint8			InnerObject;		}
struct isByte			:BaseObject	{	0:int8			InnerObject;		}
struct iShort			:BaseObject	{	0:int16			InnerObject;		}
struct iInt32			:BaseObject	{	0:int32			InnerObject;		}
struct iLong			:BaseObject	{	0:int64			InnerObject;		}
struct iFloat			:BaseObject	{	0:float			InnerObject;		}
struct iDouble			:BaseObject	{	0:double		InnerObject;		}
struct iString			:BaseObject	{	0:string		InnerObject;		}
struct iWString			:BaseObject	{	0:wstring		InnerObject;		}
struct iBool			:BaseObject	{	0:bool			InnerObject;		}
struct iUShort			:BaseObject	{	0:uint16		InnerObject;		}
struct iUInt			:BaseObject	{	0:uint32		InnerObject;		}
struct iULong			:BaseObject	{	0:uint64		InnerObject;		}
struct iSegmentArray	:BaseObject	{	0:blob			InnerObject;		}
//my app specific code...
struct iSomeObject :       BaseObject {	0:SampleOrder	InnerObject;		}
struct iTest			:BaseObject {	0:Test			InnerObject;		}

```

**Comment by ara-ayvazyan** [comment]
How about generics?
```
struct Box<T> : BaseObject
{
    0: T InnerObject;
}
```

**Comment by chwarr** [comment]
Let's assume you had a union (it's something that we're in the process of designing [no ETA], and it can be simulated if needed). Even with that, I'm not quite sure how it would help you solve the problem you're trying to solve. Can you write some pseudo-code to demonstrate how you'd use such functionality?

E.g.,

```
union SomeSummationType {
    0: int32 i1;
    1: int32 i2;
    2: SampleOrder so;
    ...
}
```

**Comment by NYProgrammer** [comment]
If I had union, I would write my struct like this - 

    ...struct RemoteObjectWrapper:BaseObject
{
    0: int32 ServiceAdapterId;
    1: int32 MethodId;
   2: bonded<BaseObject> InnerObject;
3: union AdditionalData{
int 32 iData,
vector<int32> vData.
....

}
}

**Comment by chwarr** [comment]
Thanks for the example. What you can do in that case is until unions are baked into the language is something like the following:

```
enum AdditionalDataKind {
    ADK_NONE,
    ADK_INT32,
    ADK_VEC_INT32,
   ...
}

struct AdditionalData
{
    0: AdditionalDataKind Kind = ADK_NONE;

    1: int32 iData;
    2: vector<int32> vData;
    ...
}
```

Since fields set to their default value will be omitted, only the interesting data will be serialized. The code producing and consuming will need to manually set and inspect the Kind value, and the enum and the struct will need to be kept in sync.

Keep in mind that sub-structs can never be omitted, so if you need to use a sub-struct in `AdditionalData`,  you'll want to wrap it in `nullable`.

It's not the most pleasant, but it works today. :-) Proper union support will make this much easier.

**Comment by NYProgrammer** [comment]
Sorry I know you closed this already but I am not sure how that will solve my problem...I will now have to send all the data to the other side of the wire even though I want it to contain only one member

**Comment by chwarr** [comment]
At the moment, I'm just focusing on the `AdditionalData` part of this. As I understand this question, the `AdditionalData` is completely separate from the `MethodId` + `InnerObject` part of the message that we were talking about in https://github.com/Microsoft/bond/issues/794. In other words, my [earlier comment](https://github.com/Microsoft/bond/issues/799#issuecomment-367549316) was solely about how to represent a union/variant in today's Bond. If there's some interplay between the two, can you expand on that?

While the `AdditionalData` struct looks large, since only one field at a time will be populated with data, it will serialize just the "interesting" data. All of the other fields are optional and will have their default values, so they will not be serialized.

For a more concrete example, to send a `vector<int32>` in an `AdditionalData` struct in C#, you'd write code like:

```cs
var ad = new AdditionalData {
    Kind = AdditionalDataKind.ADK__VEC_INT32,
    vData = new List<int> { 1, 2, 3, 4 }
};
```

When this is serialized in something like Compact Binary, the payload will be, roughly:

```
<ID=0, TYPE=INT32>
1
<ID=2, TYPE=LIST>
<LIST_ELEM_TYPE=INT32>
<LIST_LEN=4>
1
2
3
4
<END-OF-STRUCT-MARKER>
```

Notice that there is no `<ID=1, TYPE=INT32> 0` in the serialized data.

At runtime in the application performing serialization/deserialization, there will be some memory overhead for the extra, unused fields in C# `AdditionalData` class. That's one of the things my forthcoming design for proper union support aims to solve. I believe I can get the in-memory size of a union to be the size of its largest member plus some constant bookkeeping.

Does this address your concern?

**Comment by chwarr** [comment]
I believe this has been answered, so I'm going to close this issue. Please re-open if needed.
