### ISSUE TITLE
why the field name namespace is a reserved keyword?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/bond#852]
What's the reason having `namespace` be reserved keyword. Trying to make metric bond definition where metric has a namespace. Forced to use non human readable `ns` or long `metricNamespace`. Both options feel wrong

**Comment by chwarr** [comment]
"namespace" is a keyword in both C++ and C# and cannot be used to name an identifier. The following C++ struct will not compile:

```
struct foo {
    bool namespace;
};
```

Nor will the following C# class:

```
class foo {
    bool namespace { get; set; }
}
```

The original architecture of Bond and the current implementation don't have a way to rename a struct or field when generating code for a specific language, so to avoid generating code that will not compile, Bond reserves the union of the C++ and C# keywords (and some other keywords that is uses itself) as reserved identifiers.

This could be worked around in C# only by using the `@` prefix for the name. The following C# class does compile:

```
class foo {
    bool @namespace { get; set; }
}
```

Since the `@` prefix is not a general solution to the problem in all languages, I'd be hesitant to implement it for just C#. I don't want to make it easy to accidentally define a schema that only works in one language. That defeats much of the point of a cross-language library like Bond.
