### ISSUE TITLE
C++ : export-attribute not applied to enums

### ISSUE THREAD

**Issue by zvrba** [Microsoft/bond#861]
Free-standing functions `FromString`, `ToString`, etc. are generated for enums. When I invoke Bond compiler with `--header=\"QS_exports.h\" --export-attribute=QS_API`, this attribute is _not_ applied to these functions, an example from the generated types file:

```
const std::string& ToString(enum DeviceType value);
```

This in turn makes it impossible to use these functions when the generated code is compiled as DLL. Interestingly, `#include "QS_exports.h"` is present in the file.

As a workaround, I use functions `GetValueToNameMap` and `GetNameToValueMap`, which are defined inline in the header file, but this is.. quite inelegant.

**Comment by ara-ayvazyan** [comment]
The `--export-attribute` is used in generated `_apply.cpp` file only. It is meant for [pre-compiling](https://microsoft.github.io/bond/manual/bond_cpp.html#optimizing-build-time) de/serialization code into a [DLL](https://github.com/Microsoft/bond/tree/master/examples/cpp/core/dll), and not the struct itself along with related functionality.

**Comment by zvrba** [comment]
Ah, I understand now. Then I have a feature request:

- Add support for pre-compiling the struct code to a DLL/LIB
- Alternatively, generate it inline

**Comment by chwarr** [comment]
Generating the struct code in a static library is already available. There's an example that demonstrates [this](https://github.com/Microsoft/bond/tree/master/examples/cpp/core/static_library). It's written in CMake, so you will need to adapt this to whatever build system you're using.

Metadata access is working in the [DLL example](https://github.com/Microsoft/bond/tree/master/examples/cpp/core/dll), so there's probably something slightly different between that example and the UUID project. Could this project be minimized to just the problem so that we can look deeper?

**Comment by zvrba** [comment]
Cool, thanks for the quick fix.
