### ISSUE TITLE
How does bond deal with schema field name changes?

### ISSUE THREAD

**Issue by donners77** [Microsoft/bond#90]
Hi.  Thank you for open sourcing this library.

Suppose we had:

struct Record
{
    0: string Name;
}

which later was changed to:

struct Record2
{
    0: string FirstName;
}

How do you define a transform in bond of the data stored in Record to Record2 ? Or is this beyond the scope of bond?

**Comment by sapek** [comment]
Are you thinking about compatibility of serialized data? 

For binary formats names don't matter, so changing a name is not a breaking change. 

Obviously changing names may be a breaking change for text protocols like JSON and Xml. Struct names usually don't matter (an exception is [Xml with namespaces](https://microsoft.github.io/bond/manual/bond_cs.html#xml)) but renaming a field is always a breaking change. SimpleJSON protocol allows you to remap field names using [`JsonName` attribute](https://microsoft.github.io/bond/manual/bond_cpp.html#simple-json), e.g.:

    struct Record2
    {
        [JsonName("Name")]
        0: string FirstName;
    }

**Comment by donners77** [comment]
Thank you.

Yes, I was thinking about the compatibility of serialized data.
Also what facilities are available for dealing with changes in schema.

From reading the "Young Person’s Guide to C# Bond" I noticed there is:
- polymorphism (if new fields are added)
- converters (for changing the data type of a field)

Are there any other facilities for compatibility / conversion as schema is modified over time?

**Comment by sapek** [comment]
The best practice is to only make non-breaking schema changes (adding/removing optional fields) and then, in general, you don't have to do anything to handle schema changes. This is because with non-breaking changes Bond is forward and backward compatible, i.e. old code can read new data and new code can read old data. 

Changes which are breaking and thus should be avoided are adding/removing required fields and changing changing type or default value of an existing field. Also adding additional *bases* to existing inheritance hierarchy is a breaking change (you can of course derive additional schemas from existing ones w/o breaking anything).
