### ISSUE TITLE
Any reason why projects do not have other projects as references?

### ISSUE THREAD

**Issue by redknightlois** [Microsoft/bond#94]
The by product is that you need to try serveral builds for Bond to properly build in a fresh machine. 

See reference image:
![references](https://cloud.githubusercontent.com/assets/1045411/10944219/e59f9b2e-82f6-11e5-9b51-3c4b6173dd9b.png)

**Comment by sapek** [comment]
If you build the cs.sln solution than everything builds in one go, whether you use Visual Studio, [msbuild](https://github.com/Microsoft/bond/blob/master/appveyor.yml#L192) or [xbuild](https://github.com/Microsoft/bond/blob/master/.travis.yml#L85). Am I missing something here?

**Comment by redknightlois** [comment]
You need a couple of Ctrl-Shift-B in VS2015 to make it compile. Project references modify the build dependencies and therefore the build order inside Visual Studio. As such a dependency does not exist because the hint is based on the binary output not the project itself those things can happen. 

If there is no reason behind the missing link, I will issue a PR for it ( pretty simple to fix )

**Comment by sapek** [comment]
There was a reason: an internal build system we used didn't work correctly with project dependencies. We might not care about it anymore but I would have to verify. 

However Build Solution command absolutely should rebuild all the projects in the right order in one go. I have just tested it on a freshly cloned repo. Could you send logs from a case that doesn't rebuild everything the first time?

**Comment by redknightlois** [comment]
Cannot repro it anymore :(

**Comment by sapek** [comment]
I don't know if this is what you've originally encountered, however if you are building on a network behind a proxy and forget to set `HTTP_PROXY` environment variable then `cabal` may fail during Bond compiler build because it can't download Haskell packages. It probably depends on the network configuration but at least in our setup the outgoing connections `cabal` makes aren't terminated immediately so the result could be that the build eventually succeeded after trying many times.
