### ISSUE TITLE
Using external RapidJSON Version 1.1.0

### ISSUE THREAD

**Issue by KerstinKeller** [microsoft/bond#959]
So I am trying to get the Bond library to compile, and I am wondering, what external RapidJSON version is Bond supposed to work with. I want to use the released download `tar.gz` files to build Bond, and since these don't include submodules, I will externally install Rapidjson.

If I am using an external RapidJSON Version of `1.1.0`, the `find_package()` approach is not working.
RapidJSON 1.1.0 sets the variable `RAPIDJSON_INCLUDE_DIRS` but in the master it changed to `RapidJSON_INCLUDE_DIRS`.
Bond is using the latter `RapidJSON_INCLUDE_DIRS`.

https://github.com/Microsoft/bond/blob/1d2886f05ed10d0ea009d70b2c17a3004f0a6698/cmake/Config.cmake#L189-L193

What is the recommended way? Should I install a newer (non-released) version of RapidJSON?

**Comment by chwarr** [comment]
Bond should work with newer versions of RapidJSON. It looks like we've only tests compatibility with v1.0.0 and v1.1.0 recently.

The ability to use a RapidJSON CMake package instead of the submodule was added in commit 67eec236eb87f59b76a98ed21ffe812cd09d3cdf. It looks like the person who added this only tested against a newer version of RapidJSON.

Options I see:

1. Use a newer version of RapidJSON. If there are issues, report them here.
1. Config.cmake could be updated to fallback to `RAPIDJSON_INCLUDE_DIRS` if `RapidJSON_INCLUDE_DIRS` is not set.
    * Has the name of the entire package changed? E.g., should the fallback actually be from `find_package(RapidJSON ...)` to `find_package(RAPIDJSON ...)`?

**Comment by KerstinKeller** [comment]
Thanks for the answer.

The thing is, there is no newer "version" of RapidJSON (there are many commits on master, but no actual version was release since 1.1.0.) I would rather use a tagged version instead of a random commit.

The fallback to `${RAPIDJSON_INCLUDE_DIRS}` sounds reasonable, though I think it would be possible to just add both to `include_directories` since, if not set, they will just be an empty string.

```
include_directories ( 
  ${RapidJSON_INCLUDE_DIRS}
  ${RAPIDJSON_INCLUDE_DIRS}
)
```

**Comment by chwarr** [comment]
I'd feel a more comfortable testing whether the value is defined and conditionally including it instead of relying on an undefined variable expanding to the empty string, if that approach would work. Both `if (var)` and `if (DEFINED var)` have the behavior that we want here, and `if (var)` also tests for the empty string, so maybe something like this:

```
if (RapidJSON_INCLUDE_DIRS)
    include_directories(${RapidJSON_INCLUDE_DIRS})
endif()
if (RAPIDJSON_INCLUDE_DIRS)
    include_directories(${RAPIDJSON_INCLUDE_DIRS})
endif()
```

Is this something you would be interested in submitting as a PR?

**Comment by chwarr** [comment]
The RapidJSON submodule had its commit bumped to one from April 10, 2020 in commit https://github.com/microsoft/bond/commit/d7cb60367a8fd513aa48c02740dc567950ead192 (to keep up with evolving GCC warnings). I'm not sure if this has broken you more or unbroken you.

If there's still something here, can you reply to this issue with the current state?
