### ISSUE TITLE
[C#] Compile error

### ISSUE THREAD

**Issue by Jing-lan** [microsoft/bond#990]
when I tried to compile Bond project by dotnet msbuild cs\cs.sln, I got an error "D:\HC\bond\cs\Compiler.csproj(93,5): error MSB3073: The command "cmake D:\HC\bond\cs\..\compiler  -Wno-dev" exited with code 1."

**Comment by chwarr** [comment]
If you run the build at a higher verbosity level (`dotnet msbuild /v:diag cs\cs.sln`), you should get more details about what happened. It looks like a dependency that CMake needs to build gbc may not be able to be found.

Make sure you're running the build from a MSVC command prompt with the C++ toolchain installed.

**Comment by chwarr** [comment]
Haven't heard anything about this in a while, so I'm going to close this issue. Please re-open it if you have more details or need more help.

**Comment by vishnu4** [comment]
I'm getting this same thing after upgrading from bond 7 to 8 or 9.  Detailed output is below:

Target SetBondOutputDirectory:
5>Target BondCheckDuplicateCodegen:
5>  Task "RemoveDuplicates"
5>  Done executing task "RemoveDuplicates".
5>  Task "Error" skipped, due to false condition; ( '@(BondCodegen)' != '@(_BondCodegenFiltered)' ) was evaluated as ( 'Asimov\SDOutgoingRequest.bond;GenevaLogging\IfxEvents.bond' != 'Asimov\SDOutgoingRequest.bond;GenevaLogging\IfxEvents.bond' ).
5>Target BondCodegenCs:
5>  Building target "BondCodegenCs" completely.
5>  Output file "obj/Debug/netstandard2.0/bondcodegen.done" does not exist.
5>  Task "Error" skipped, due to false condition; ('$(_bond_common_props_imported)' != 'true') was evaluated as ('true' != 'true').
5>  Task "MakeDir"
5>  Done executing task "MakeDir".
5>  Task "WriteLinesToFile"
5>  Done executing task "WriteLinesToFile".
5>  Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
5>  Task "Exec"
5>    "C:\Users\Administrator\.nuget\packages\bond.csharp\9.0.3\build\..\\tools\gbc.exe" c# --import-dir="C:\Users\Administrator\.nuget\packages\bond.csharp\9.0.3\build\..\\tools\inc" --import-dir="C:\Users\Administrator\.nuget\packages\microsoft.commonschema.bond\3.3.17201.9\build\..\bond\\." --import-dir="C:\Users\Administrator\.nuget\packages\microsoft.cloud.instrumentationframework\3.2.3.1\build\native\inc\\." --jobs=-2 --namespace=bond=Bond --output-dir="obj/Debug/netstandard2.0/"  @"obj/Debug/netstandard2.0/bonddefaultcodegen.in"
5>    gbc.exe: user error (Can't find import file Ms.Qos.bond)
5>    C:\Users\Administrator\.nuget\packages\bond.csharp\9.0.3\build\Common.targets(161,5): error MSB3073: The command ""C:\Users\Administrator\.nuget\packages\bond.csharp\9.0.3\build\..\\tools\gbc.exe" c# --import-dir="C:\Users\Administrator\.nuget\packages\bond.csharp\9.0.3\build\..\\tools\inc" --import-dir="C:\Users\Administrator\.nuget\packages\microsoft.commonschema.bond\3.3.17201.9\build\..\bond\\." --import-dir="C:\Users\Administrator\.nuget\packages\microsoft.cloud.instrumentationframework\3.2.3.1\build\native\inc\\." --jobs=-2 --namespace=bond=Bond --output-dir="obj/Debug/netstandard2.0/"  @"obj/Debug/netstandard2.0/bonddefaultcodegen.in"" exited with code 1.
5>  Done executing task "Exec" -- FAILED.
5>Done building target "BondCodegenCs" in project "MSEG.ServiceDesk.Core.Logging.Legacy.csproj" -- FAILED.

**Comment by chwarr** [comment]
@vishnu4, your problem appears to be fundamentally different from the one originally reported in this issue. The original report was about trying to build Bond itself and that failing during the Haskell compilation step.

Your issue is about code generation occurring during a C# build. It says that the file Ms.Qos.bond cannot be found in any of the import directories. Bond is looking in the following directories on your machine:

1. `"C:\Users\Administrator\.nuget\packages\bond.csharp\9.0.3\build\..\\tools\inc"`
2. `"C:\Users\Administrator\.nuget\packages\microsoft.commonschema.bond\3.3.17201.9\build\..\bond\\."`
3. `"C:\Users\Administrator\.nuget\packages\microsoft.cloud.instrumentationframework\3.2.3.1\build\native\inc\\."`

Does the file "Ms.Qos.bond" exist in either of the second or third directory? (It isn't part of Bond, so it shouldn't be in the first directory.) gbc doesn't recursively look in import directories, so it will need to be in the root of the second or third directory.

* If it isn't in any of those directories, you'll need to find a location where it comes from and make sure that directory is in the `BondImportDirectory` MSBuild item. (E.g., `<ItemGroup><BondImportDirectory Include="..\..\path\to\dir\" /></ItemGroup>`)

* If it is in one of the directories, but in a subdirectory, then either the `import` statment needs a relative path (E.g., `import "subdir/Ms.Qos.bond"`) or that subdirectory needs to be added to the `BondImportDirectory` MSBuild item.

* If it is in one of the root of one of the directories, then something very odd is going on. If this is the case, can you take a [MSBuild binlog][binlog] of the build with 7.0.0 that works and one of the 9.0.3 that doesn't work and attach those to a new issue?

I looked at the changes to the codegen targets between 7.0.0 and the current master (05c57981a3f9e259526e41f1ca92c0f1a5a6d786). (GitHub.com [diff], though this link doesn't always work for me. I've reported the issue to GitHub...) There are no obvious changes to how import directories are handled between 7.0.0 and now.

[binlog]: https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log
[diff]: https://github.com/microsoft/bond/compare/7.0.0...05c57981a3f9e259526e41f1ca92c0f1a5a6d786#diff-2a25704b232866e4188ca19274093c1a90c04ac8773abe5a2dbdffcb3015c449

**Comment by vishnu4** [comment]
Thank you for your response @chwarr .  Apparently my issue is partially that when i upgrade Bond, i needed to upgrade some other nuget packages as well, namely:
```
<PackageReference Include="Microsoft.CommonSchema.Bond" Version="4.0.20036.2" />
<PackageReference Include="Microsoft.CommonSchema.Services" Version="5.2.38" />
<PackageReference Include="Microsoft.CommonSchema.Services.Autopilot" Version="5.2.38" />
<PackageReference Include="Microsoft.CommonSchema.Services.HttpClient" Version="5.2.38" />
```

which does seem to get rid of the MS.QoS error, but then gave me a 'filepathtoolong' exception.  Moving the code repo to a different path seemed to fix that, but now i'm getting the issue below.  This may not be your issue, but i had hoped that you may have a solution regardless:

5>Target RunProduceContentAssets:
5>  Using "ProduceContentAssets" task from assembly "C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\..\tools\net472/Microsoft.NET.Build.Tasks.dll".
5>  Task "ProduceContentAssets"
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018: The "ProduceContentAssets" task failed unexpectedly.
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Code\1\MSEG.EAE.Customer\MSEG.EAE.Customer.Service\MSEG.EAE.ServiceDesk.Core\src\MSEG.ServiceDesk.Core.Logging.Legacy\obj\Debug\netstandard2.0\NuGet\50747AEA4C6E85F901053D270D02A990D5F49C1C\Microsoft.CommonSchema.Services.Autopilot\5.2.38\PoliciesForAutopilot.cs'.
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at System.IO.File.WriteAllText(String path, String contents)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at Microsoft.NET.Build.Tasks.NugetContentAssetPreprocessor.Process(String originalAssetPath, String relativeOutputPath, String& pathToFinalAsset)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProduceContentAssets.ProduceContentAsset(ITaskItem contentFile)
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProduceContentAssets.ExecuteCore()
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
5>    C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(386,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
5>  Done executing task "ProduceContentAssets" -- FAILED.
5>Done building target "RunProduceContentAssets" in project "MSEG.ServiceDesk.Core.Logging.Legacy.csproj" -- FAILED.
5>
5>Done building project "MSEG.ServiceDesk.Core.Logging.Legacy.csproj" -- FAILED.
5>
5>Build FAILED.

**Comment by chwarr** [comment]
Nope, that isn't something that I've seen before. It is suspicious that the path it cannot find is over 260 chars long, the historical `MAX_PATH` limit in lots of Windows software. The .NET SDK is in the https://github.com/dotnet/sdk repo. Perhaps there's an issue there that is similar?

**Comment by vishnu4** [comment]
Yup, that was it.  even though it wasn't explicitly saying the path was too long, it still was.  thank you!

**Comment by Satch97** [comment]
I've hit the same error when compiling my .net core project using "dotnet build" on Ubuntu 20.04.

/home/satch/.nuget/packages/bond.csharp/8.0.0/build/Common.targets(161,5): error MSB3073: The command ""/home/satch/.nuget/packages/bond.csharp/8.0.0/build/../tools/gbc.exe" c# --import-dir="/home/satch/.nuget/packages/bond.csharp/8.0.0/build/../tools/inc" --import-dir="{private dependency path}" --import-dir="{private dependency path}" --import-dir="{private dependency path}" --import-dir="{private dependency path}" --jobs=-2 --namespace=bond=Bond --output-dir="obj/Debug/ubuntu.20.04-x64/"  @"obj/Debug/ubuntu.20.04-x64/bonddefaultcodegen.in"" exited with code 1. [private .csproj location]

I tried to repro on my windows 10 machine but could not, the build succeeds though bond.csharp version 9.0.1 is used in the windows build instead of 8.0.0 on the linux counterpart. I also confirmed that all paths were valid and that there were no case sensitivity errors

This is a csharp project, I ran with -v diag but could not find anymore details of the error. Do you have any pointers on what I  should be looking for or what I could share that might be helpful?

**Comment by chwarr** [comment]
@Satch97, you are probably running into a known limitation with the Bond NuGet packages: they only contain a Windows version of gbc, the Bond codegen tool. (More details in issue [#940, gbc for linux?](https://github.com/microsoft/bond/issues/940).)

Today, to use Bond on Linux (or macOS), you will need to build gbc from source (see the [README](https://github.com/microsoft/bond/blob/master/README.md) for instructions) and then, during your C# build, set the MSBuild property `BOND_COMPILER_PATH` to the _directory_ that contains the gbc executable. (For example, using the `-property:BOND_COMPILER_PATH=/path/to/dir` MSBuild command line switch or by setting the `BOND_COMPILER_PATH` environment variable before invoking MSBuild.)

Microsoft currently has no plans to produce or package official gbc binaries for Linux or macOS.

**Comment by Satch97** [comment]
Thanks @chwarr, the steps provided on #940  to build gbc + `dotnet build -p:BOND_COMPILER_PATH=/path/to/dirWithGbc` worked.
